"""
01_data_profile.py

Profiles the Open University Learning Analytics Dataset.

Every figure that appears in docs/01_data_profile.md must be produced by this script.
Nothing here is quoted from memory or from secondary sources.

Two design critical checks are included:

  Check A. Does date_unregistration agree with final_result == 'Withdrawn'?
           The project treats withdrawal as the adverse outcome and needs a date for it.
           If the two disagree, the outcome definition has to be settled before modelling.

  Check B. How many withdrawals occur before the week 4, 8 and 12 decision points?
           A student who has already left cannot be helped by an intervention at that
           point. Those students leave the risk set. If most withdrawals happen before
           week 4, the earliest decision point means something different from what the
           method doc assumes.

Usage:
    python 01_data_profile.py

Writes:
    docs/01_data_profile.md      generated report
    cache/profile_stats.json     machine readable figures for later scripts
"""

import json
from pathlib import Path

import pandas as pd

RAW = Path("data/raw")
DOCS = Path("docs")
CACHE = Path("cache")
CACHE.mkdir(exist_ok=True)
DOCS.mkdir(exist_ok=True)

# Decision points, expressed in days from module start.
# OULAD encodes all dates as days relative to the first day of the presentation.
WEEKS = {"week_4": 28, "week_8": 56, "week_12": 84}

stats = {}
lines = []


def w(s=""):
    """Write a line to the report and echo it."""
    lines.append(s)
    print(s)


# ---------------------------------------------------------------------------
# Table inventory
# ---------------------------------------------------------------------------

w("# 01. Data profile")
w()
w("Generated by `01_data_profile.py`. Do not edit by hand.")
w()
w("## Table inventory")
w()
w("| Table | Rows | Columns | Missing cells |")
w("|---|---:|---:|---:|")

small_tables = [
    "courses",
    "assessments",
    "vle",
    "studentInfo",
    "studentRegistration",
    "studentAssessment",
]

frames = {}
inventory = {}

for name in small_tables:
    df = pd.read_csv(RAW / f"{name}.csv")
    frames[name] = df
    missing = int(df.isna().sum().sum())
    inventory[name] = {
        "rows": int(len(df)),
        "columns": list(df.columns),
        "missing_cells": missing,
    }
    w(f"| {name} | {len(df):,} | {len(df.columns)} | {missing:,} |")

# studentVle is large. Count it in chunks rather than loading it whole.
vle_rows = 0
vle_students = set()
vle_date_min = None
vle_date_max = None
vle_clicks = 0

for chunk in pd.read_csv(
    RAW / "studentVle.csv",
    usecols=["id_student", "date", "sum_click"],
    dtype={"id_student": "int32", "date": "int16", "sum_click": "int32"},
    chunksize=2_000_000,
):
    vle_rows += len(chunk)
    vle_students.update(chunk["id_student"].unique().tolist())
    cmin, cmax = int(chunk["date"].min()), int(chunk["date"].max())
    vle_date_min = cmin if vle_date_min is None else min(vle_date_min, cmin)
    vle_date_max = cmax if vle_date_max is None else max(vle_date_max, cmax)
    vle_clicks += int(chunk["sum_click"].sum())

inventory["studentVle"] = {
    "rows": vle_rows,
    "unique_students": len(vle_students),
    "date_min": vle_date_min,
    "date_max": vle_date_max,
    "total_clicks": vle_clicks,
}

w(f"| studentVle | {vle_rows:,} | 5 | counted in chunks |")
w()
w(
    f"studentVle covers {len(vle_students):,} distinct students, "
    f"{vle_clicks:,} total clicks, days {vle_date_min} to {vle_date_max}."
)
w()
w(
    "Negative day values are interactions recorded before the official start of the "
    "presentation. Any feature built from a window starting at day 0 silently discards "
    "them, so the window definition is stated explicitly in the feature script."
)
w()

stats["inventory"] = inventory

# ---------------------------------------------------------------------------
# Cohort structure
# ---------------------------------------------------------------------------

info = frames["studentInfo"]
reg = frames["studentRegistration"]
courses = frames["courses"]

w("## Cohort structure")
w()

n_reg = len(info)
n_students = info["id_student"].nunique()
n_modules = info["code_module"].nunique()
n_pres = info["code_presentation"].nunique()
n_module_pres = info.groupby(["code_module", "code_presentation"]).ngroups

w(f"- Registrations (rows in studentInfo): {n_reg:,}")
w(f"- Distinct students: {n_students:,}")
w(f"- Modules: {n_modules}")
w(f"- Presentations: {n_pres}")
w(f"- Module presentation combinations: {n_module_pres}")
w()

repeat = n_reg - n_students
w(
    f"{repeat:,} registrations belong to students who appear more than once. A student "
    "who takes two modules is two rows. Any train and test split that ignores this "
    "leaks the same person across both sides, so splits are made at student level, not "
    "row level."
)
w()

stats["cohort"] = {
    "registrations": n_reg,
    "distinct_students": n_students,
    "modules": n_modules,
    "presentations": n_pres,
    "module_presentations": n_module_pres,
    "repeat_registrations": repeat,
}

# ---------------------------------------------------------------------------
# Outcome distribution
# ---------------------------------------------------------------------------

w("## Outcome distribution")
w()

outcome = info["final_result"].value_counts()
outcome_pct = (outcome / len(info) * 100).round(2)

w("| final_result | Count | Share |")
w("|---|---:|---:|")
for k in outcome.index:
    w(f"| {k} | {outcome[k]:,} | {outcome_pct[k]:.2f}% |")
w()

withdrawn = int(outcome.get("Withdrawn", 0))
withdrawal_rate = withdrawn / len(info) * 100

w(f"**Withdrawal rate: {withdrawal_rate:.2f}%** ({withdrawn:,} of {len(info):,}).")
w()
w(
    "This is the figure to cite. It is a distance learning population and is not "
    "comparable to residential completion statistics."
)
w()

stats["outcomes"] = {
    "counts": {str(k): int(v) for k, v in outcome.items()},
    "withdrawal_rate_pct": round(withdrawal_rate, 4),
}

# Withdrawal by module presentation, to show how much it varies.
by_mp = (
    info.assign(withdrew=(info["final_result"] == "Withdrawn").astype(int))
    .groupby(["code_module", "code_presentation"])
    .agg(n=("withdrew", "size"), withdrew=("withdrew", "sum"))
)
by_mp["rate_pct"] = (by_mp["withdrew"] / by_mp["n"] * 100).round(2)

w("### Withdrawal rate by module presentation")
w()
w("| Module | Presentation | N | Withdrew | Rate |")
w("|---|---|---:|---:|---:|")
for (mod, pres), row in by_mp.iterrows():
    w(f"| {mod} | {pres} | {int(row['n']):,} | {int(row['withdrew']):,} | {row['rate_pct']:.2f}% |")
w()
w(
    f"Range across cohorts: {by_mp['rate_pct'].min():.2f}% to {by_mp['rate_pct'].max():.2f}%. "
    "A single pooled rate hides this. Models are evaluated within cohort as well as pooled."
)
w()

stats["withdrawal_by_module_presentation"] = {
    f"{m}_{p}": {"n": int(r["n"]), "withdrew": int(r["withdrew"]), "rate_pct": float(r["rate_pct"])}
    for (m, p), r in by_mp.iterrows()
}

# ---------------------------------------------------------------------------
# Check A. Outcome definition consistency
# ---------------------------------------------------------------------------

w("## Check A. Does the withdrawal date agree with the outcome label?")
w()

merged = info.merge(
    reg, on=["id_student", "code_module", "code_presentation"], how="left", validate="one_to_one"
)

has_unreg = merged["date_unregistration"].notna()
is_withdrawn = merged["final_result"] == "Withdrawn"

both = int((has_unreg & is_withdrawn).sum())
unreg_not_withdrawn = int((has_unreg & ~is_withdrawn).sum())
withdrawn_no_unreg = int((~has_unreg & is_withdrawn).sum())
neither = int((~has_unreg & ~is_withdrawn).sum())

w("| | Labelled Withdrawn | Not labelled Withdrawn |")
w("|---|---:|---:|")
w(f"| Has unregistration date | {both:,} | {unreg_not_withdrawn:,} |")
w(f"| No unregistration date | {withdrawn_no_unreg:,} | {neither:,} |")
w()

if unreg_not_withdrawn or withdrawn_no_unreg:
    w(
        f"**The two disagree on {unreg_not_withdrawn + withdrawn_no_unreg:,} registrations.** "
        "The outcome definition must be settled before any model is fit. Whichever "
        "definition is chosen, the disagreement count is reported alongside it."
    )
else:
    w("The two agree exactly. Either can be used as the outcome definition.")
w()

stats["check_a"] = {
    "unreg_and_withdrawn": both,
    "unreg_not_withdrawn": unreg_not_withdrawn,
    "withdrawn_no_unreg": withdrawn_no_unreg,
    "neither": neither,
}

# ---------------------------------------------------------------------------
# Check B. Time slice feasibility
# ---------------------------------------------------------------------------

w("## Check B. Is anyone left to help at each decision point?")
w()
w(
    "At a decision point on day D, a student is in the risk set only if they have not "
    "already unregistered. Students who left before D cannot be affected by an "
    "intervention at D and are removed. The table below shows what is left."
)
w()
w("| Decision point | Day | Already gone | Still in risk set | Withdraw later | Later rate |")
w("|---|---:|---:|---:|---:|---:|")

unreg_day = merged["date_unregistration"]

slice_stats = {}
for label, day in WEEKS.items():
    gone = int((unreg_day < day).sum())
    at_risk = len(merged) - gone
    later = int((unreg_day >= day).sum())
    later_rate = later / at_risk * 100 if at_risk else 0.0
    w(f"| {label} | {day} | {gone:,} | {at_risk:,} | {later:,} | {later_rate:.2f}% |")
    slice_stats[label] = {
        "day": day,
        "already_gone": gone,
        "at_risk": at_risk,
        "withdraw_later": later,
        "later_rate_pct": round(later_rate, 4),
    }
w()

early = slice_stats["week_4"]["already_gone"]
early_share = early / withdrawn * 100 if withdrawn else 0.0
w(
    f"{early:,} registrations unregister before day 28, which is {early_share:.1f}% of all "
    "withdrawals. Those students are outside the reach of any intervention timed at week 4 "
    "or later. This is a ceiling on what allocation at these decision points can achieve, "
    "and it belongs in the limitations before any result is reported."
)
w()

stats["check_b"] = slice_stats
stats["check_b"]["withdrawals_before_week_4_share_pct"] = round(early_share, 4)

# ---------------------------------------------------------------------------
# Missingness in candidate features
# ---------------------------------------------------------------------------

w("## Missingness in studentInfo")
w()
w("| Column | Missing | Share |")
w("|---|---:|---:|")
miss = info.isna().sum()
for col in info.columns:
    w(f"| {col} | {int(miss[col]):,} | {miss[col] / len(info) * 100:.2f}% |")
w()

stats["studentinfo_missing"] = {c: int(miss[c]) for c in info.columns}

# ---------------------------------------------------------------------------
# Module lengths
# ---------------------------------------------------------------------------

w("## Module lengths")
w()
w("| Module | Presentation | Length (days) |")
w("|---|---|---:|")
for _, r in courses.iterrows():
    w(f"| {r['code_module']} | {r['code_presentation']} | {int(r['module_presentation_length'])} |")
w()
w(
    f"Lengths run from {int(courses['module_presentation_length'].min())} to "
    f"{int(courses['module_presentation_length'].max())} days. Day 84 is a different "
    "fraction of the way through a short module than a long one, so decision points are "
    "recorded in both absolute days and proportion elapsed."
)
w()

stats["module_lengths"] = {
    f"{r['code_module']}_{r['code_presentation']}": int(r["module_presentation_length"])
    for _, r in courses.iterrows()
}

# ---------------------------------------------------------------------------
# Write outputs
# ---------------------------------------------------------------------------

(DOCS / "01_data_profile.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "profile_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print("Wrote docs/01_data_profile.md")
print("Wrote cache/profile_stats.json")
