"""
02_cohort.py

Builds the analysis population for the education domain.

Three things happen here and nowhere else:

  1. Exclusions are applied and counted. Every exclusion has a stated reason and a
     number. Nothing is dropped silently.

  2. The outcome is defined once. docs/01_data_profile.md found 102 registrations
     where the Withdrawn label and the unregistration date disagree. The project needs
     a withdrawal DATE, because reachability at a decision point depends on it, so the
     date is authoritative and the disagreement is reported rather than hidden.

  3. Folds are assigned at student level, not row level. 3,808 registrations belong to
     students who appear more than once. Assigning folds per row would put the same
     person in train and test. The assignment is a deterministic hash of the student id,
     so it is stable across reruns and across every script downstream.

Usage:
    python 02_cohort.py

Reads:
    data/raw/studentInfo.csv
    data/raw/studentRegistration.csv
    data/raw/courses.csv

Writes:
    data/processed/cohort.parquet    analysis population, one row per registration
    docs/02_cohort.md                generated report
    cache/cohort_stats.json          machine readable figures
"""

import hashlib
import json
from pathlib import Path

import pandas as pd

RAW = Path("data/raw")
PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")
for p in (PROC, DOCS, CACHE):
    p.mkdir(parents=True, exist_ok=True)

N_FOLDS = 5
FOLD_SALT = "marginal-oulad-v1"  # changing this reshuffles every split. Do not change.

DECISION_DAYS = [0, 28, 56, 84]

stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


def assign_fold(student_id: int) -> int:
    """Deterministic fold from a stable hash. Same id gives the same fold forever."""
    h = hashlib.sha256(f"{FOLD_SALT}:{student_id}".encode()).hexdigest()
    return int(h, 16) % N_FOLDS


# ---------------------------------------------------------------------------
# Load and join
# ---------------------------------------------------------------------------

info = pd.read_csv(RAW / "studentInfo.csv")
reg = pd.read_csv(RAW / "studentRegistration.csv")
courses = pd.read_csv(RAW / "courses.csv")

df = info.merge(
    reg,
    on=["id_student", "code_module", "code_presentation"],
    how="left",
    validate="one_to_one",
).merge(
    courses,
    on=["code_module", "code_presentation"],
    how="left",
    validate="many_to_one",
)

n_start = len(df)

w("# 02. Cohort")
w()
w("Generated by `02_cohort.py`. Do not edit by hand.")
w()
w("## Exclusions")
w()
w("| Step | Reason | Removed | Remaining |")
w("|---|---|---:|---:|")
w(f"| 0 | Starting registrations | | {n_start:,} |")

exclusions = {}

# --- Exclusion 1. Unregistered before the module started. -------------------
# These students never began. A retention population cannot contain people who did
# not start, and no intervention during the module could have reached them.

mask_prestart = df["date_unregistration"] < 0
n_prestart = int(mask_prestart.sum())
df = df[~mask_prestart].copy()
exclusions["unregistered_before_day_0"] = n_prestart
w(f"| 1 | Unregistered before day 0, never started | {n_prestart:,} | {len(df):,} |")

# --- Exclusion 2. Unregistered after the module ended. ----------------------
# Not a real pattern. Recorded because an unexplained exclusion is worse than a
# documented one.

mask_late = df["date_unregistration"] > df["module_presentation_length"]
n_late = int(mask_late.sum())
df = df[~mask_late].copy()
exclusions["unregistered_after_module_end"] = n_late
w(f"| 2 | Unregistered after module end, data error | {n_late:,} | {len(df):,} |")

w()
n_final = len(df)
stats["exclusions"] = exclusions
stats["n_start"] = n_start
stats["n_analysis"] = n_final

w(
    f"Analysis population: **{n_final:,} registrations**, "
    f"{n_start - n_final:,} excluded ({(n_start - n_final) / n_start * 100:.2f}%)."
)
w()

# ---------------------------------------------------------------------------
# Outcome definition
# ---------------------------------------------------------------------------

w("## Outcome definition")
w()

df["withdrew"] = df["date_unregistration"].notna().astype(int)
df["withdrawal_day"] = df["date_unregistration"]

n_withdrew = int(df["withdrew"].sum())
rate = n_withdrew / n_final * 100

w(
    "`withdrew = 1` if an unregistration date is present. The date is authoritative "
    "because reachability at a decision point depends on timing, which the label alone "
    "does not carry."
)
w()

label_withdrawn = df["final_result"] == "Withdrawn"
disagree_no_date = int((label_withdrawn & (df["withdrew"] == 0)).sum())
disagree_has_date = int((~label_withdrawn & (df["withdrew"] == 1)).sum())

w(f"- Withdrawals in the analysis population: **{n_withdrew:,}**")
w(f"- Withdrawal rate: **{rate:.2f}%**")
w(f"- Labelled Withdrawn but no unregistration date: {disagree_no_date:,}")
w(f"- Has unregistration date but a different label: {disagree_has_date:,}")
w()
w(
    f"The {disagree_no_date + disagree_has_date:,} disagreeing registrations are kept in "
    "the population and classified by date. This is a choice, not a fact about the data, "
    "and any result sensitive to it must be reported both ways."
)
w()

stats["outcome"] = {
    "withdrew": n_withdrew,
    "withdrawal_rate_pct": round(rate, 4),
    "label_withdrawn_no_date": disagree_no_date,
    "date_but_other_label": disagree_has_date,
}

# ---------------------------------------------------------------------------
# Reachability at each decision point
# ---------------------------------------------------------------------------

w("## Reachability at each decision point")
w()
w(
    "A student is reachable at day D if they have not already unregistered. The "
    "addressable share is the fraction of all withdrawals that are still ahead at D."
)
w()
w("| Day | Reachable | Withdraw at or after D | Addressable share of all withdrawals |")
w("|---:|---:|---:|---:|")

reach = {}
for d in DECISION_DAYS:
    gone = int((df["withdrawal_day"] < d).sum())
    reachable = n_final - gone
    later = int((df["withdrawal_day"] >= d).sum())
    share = later / n_withdrew * 100 if n_withdrew else 0.0
    w(f"| {d} | {reachable:,} | {later:,} | {share:.2f}% |")
    reach[str(d)] = {
        "reachable": reachable,
        "withdraw_at_or_after": later,
        "addressable_share_pct": round(share, 4),
    }
w()

d0 = reach["0"]["addressable_share_pct"]
d28 = reach["28"]["addressable_share_pct"]
w(
    f"Day 0 addresses {d0:.1f}% of withdrawals by construction. Day 28 addresses "
    f"{d28:.1f}%. The gap between them is the share of withdrawals that only a day 0 "
    "decision point can reach, and it is the reason day 0 is included."
)
w()

stats["reachability"] = reach

# ---------------------------------------------------------------------------
# Fold assignment
# ---------------------------------------------------------------------------

w("## Fold assignment")
w()

df["fold"] = df["id_student"].map(assign_fold)

n_students = df["id_student"].nunique()
multi = int(len(df) - n_students)

fold_tbl = df.groupby("fold").agg(
    registrations=("withdrew", "size"),
    students=("id_student", "nunique"),
    withdrew=("withdrew", "sum"),
)
fold_tbl["rate_pct"] = (fold_tbl["withdrew"] / fold_tbl["registrations"] * 100).round(2)

w(
    f"{N_FOLDS} folds, assigned by deterministic hash of `id_student`. "
    f"{multi:,} registrations belong to repeat students, so row level assignment would "
    "leak. Every script downstream uses this column and never reshuffles."
)
w()
w("| Fold | Registrations | Students | Withdrew | Rate |")
w("|---:|---:|---:|---:|---:|")
for f, r in fold_tbl.iterrows():
    w(
        f"| {f} | {int(r['registrations']):,} | {int(r['students']):,} | "
        f"{int(r['withdrew']):,} | {r['rate_pct']:.2f}% |"
    )
w()

# Verify no student spans folds.
spans = df.groupby("id_student")["fold"].nunique()
n_spanning = int((spans > 1).sum())
if n_spanning:
    w(f"**FAIL: {n_spanning:,} students appear in more than one fold.**")
else:
    w("Check passed: no student appears in more than one fold.")
w()

stats["folds"] = {
    "n_folds": N_FOLDS,
    "salt": FOLD_SALT,
    "students_spanning_folds": n_spanning,
    "per_fold": {
        int(f): {
            "registrations": int(r["registrations"]),
            "students": int(r["students"]),
            "withdrew": int(r["withdrew"]),
            "rate_pct": float(r["rate_pct"]),
        }
        for f, r in fold_tbl.iterrows()
    },
}

# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

keep = [
    "id_student",
    "code_module",
    "code_presentation",
    "module_presentation_length",
    "gender",
    "region",
    "highest_education",
    "imd_band",
    "age_band",
    "num_of_prev_attempts",
    "studied_credits",
    "disability",
    "date_registration",
    "final_result",
    "withdrew",
    "withdrawal_day",
    "fold",
]

df[keep].to_parquet(PROC / "cohort.parquet", index=False)
(DOCS / "02_cohort.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "cohort_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print(f"Wrote data/processed/cohort.parquet  ({n_final:,} rows)")
print("Wrote docs/02_cohort.md")
print("Wrote cache/cohort_stats.json")
