"""
03_features.py

Builds one feature table per decision point for the education domain.

The rule this script exists to enforce: at a decision point on day D, a feature may use
information available strictly before D and nothing else. A model that sees day 90
clickstream when predicting at day 28 will look excellent and mean nothing.

Three guards, all of which halt the script rather than warn:

  Guard 1. The daily activity panel is filtered to date < D before any aggregation.
           Asserted after filtering, not assumed.

  Guard 2. Assessments are filtered on date_submitted < D. Scores are only known once
           submitted and marked, so an unsubmitted assessment contributes nothing.

  Guard 3. The population at D contains only students still reachable at D. A student
           who unregistered on day 20 is not a prediction target at day 28. Their
           outcome is already realised.

The outcome at D is: does this student unregister at some point at or after D. That is
the quantity an intervention at D could change.

Note on materials: distinct VLE materials accessed is not built. Daily distinct site
counts cannot be summed into a slice level distinct count without over counting, and an
approximate figure presented as exact is the kind of thing this project does not do.
Click volume and activity pattern carry most of the same signal.

Usage:
    python 03_features.py

Reads:
    data/processed/cohort.parquet
    data/raw/studentVle.csv
    data/raw/studentAssessment.csv
    data/raw/assessments.csv

Writes:
    data/processed/features_d{D}.parquet   one per decision point
    data/processed/daily_panel.parquet     intermediate, reused across slices
    docs/03_features.md
    cache/feature_stats.json
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

RAW = Path("data/raw")
PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

DECISION_DAYS = [0, 28, 56, 84]
MAX_DAY = max(DECISION_DAYS)

# Sentinel for "never active in the window". A large positive value, because the feature
# is days since last activity and never active should look worse than long ago.
NEVER_ACTIVE = 999

stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


# ---------------------------------------------------------------------------
# Daily activity panel
# ---------------------------------------------------------------------------

cohort = pd.read_parquet(PROC / "cohort.parquet")

panel_path = PROC / "daily_panel.parquet"

if panel_path.exists():
    daily = pd.read_parquet(panel_path)
    print(f"Reusing daily panel: {len(daily):,} rows")
else:
    print("Building daily panel from studentVle.csv (chunked)")
    parts = []
    for chunk in pd.read_csv(
        RAW / "studentVle.csv",
        usecols=["code_module", "code_presentation", "id_student", "date", "sum_click"],
        dtype={"id_student": "int32", "date": "int16", "sum_click": "int32"},
        chunksize=2_000_000,
    ):
        # Everything at or after the last decision point is irrelevant to every slice.
        chunk = chunk[chunk["date"] < MAX_DAY]
        parts.append(
            chunk.groupby(
                ["code_module", "code_presentation", "id_student", "date"], observed=True
            )
            .agg(clicks=("sum_click", "sum"), events=("sum_click", "size"))
            .reset_index()
        )

    daily = (
        pd.concat(parts, ignore_index=True)
        .groupby(["code_module", "code_presentation", "id_student", "date"], observed=True)
        .agg(clicks=("clicks", "sum"), events=("events", "sum"))
        .reset_index()
    )
    daily.to_parquet(panel_path, index=False)
    print(f"Wrote daily panel: {len(daily):,} rows")

assert daily["date"].max() < MAX_DAY, "Daily panel contains days at or beyond the last slice"

# ---------------------------------------------------------------------------
# Assessments
# ---------------------------------------------------------------------------

sa = pd.read_csv(RAW / "studentAssessment.csv")
assess = pd.read_csv(RAW / "assessments.csv")
sa = sa.merge(
    assess[["id_assessment", "code_module", "code_presentation", "assessment_type", "date"]],
    on="id_assessment",
    how="left",
    validate="many_to_one",
).rename(columns={"date": "deadline_day"})

# ---------------------------------------------------------------------------
# Report header
# ---------------------------------------------------------------------------

w("# 03. Features")
w()
w("Generated by `03_features.py`. Do not edit by hand.")
w()
w(
    "One table per decision point. At day D, every feature uses data strictly before D "
    "and the population is restricted to students not yet unregistered at D."
)
w()

KEYS = ["id_student", "code_module", "code_presentation"]

STATIC = [
    "gender",
    "region",
    "highest_education",
    "imd_band",
    "age_band",
    "num_of_prev_attempts",
    "studied_credits",
    "disability",
    "date_registration",
    "module_presentation_length",
]

slice_stats = {}

for D in DECISION_DAYS:

    # --- Guard 3. Population reachable at D. -------------------------------
    pop = cohort[(cohort["withdrawal_day"].isna()) | (cohort["withdrawal_day"] >= D)].copy()
    assert (
        pop["withdrawal_day"].dropna() >= D
    ).all(), f"Population at day {D} contains students who already left"

    pop["outcome"] = pop["withdrawal_day"].notna().astype(int)

    # --- Guard 1. Activity strictly before D. ------------------------------
    act = daily[daily["date"] < D]
    if len(act):
        assert act["date"].max() < D, f"Activity leak at day {D}"

    if len(act):
        agg = (
            act.groupby(KEYS, observed=True)
            .agg(
                clicks_total=("clicks", "sum"),
                events_total=("events", "sum"),
                active_days=("date", "nunique"),
                last_active_day=("date", "max"),
                first_active_day=("date", "min"),
            )
            .reset_index()
        )

        recent7 = (
            act[act["date"] >= D - 7]
            .groupby(KEYS, observed=True)["clicks"]
            .sum()
            .rename("clicks_last7")
            .reset_index()
        )
        recent14 = (
            act[act["date"] >= D - 14]
            .groupby(KEYS, observed=True)["clicks"]
            .sum()
            .rename("clicks_last14")
            .reset_index()
        )
        prestart = (
            act[act["date"] < 0]
            .groupby(KEYS, observed=True)["clicks"]
            .sum()
            .rename("clicks_prestart")
            .reset_index()
        )

        agg = agg.merge(recent7, on=KEYS, how="left").merge(recent14, on=KEYS, how="left")
        agg = agg.merge(prestart, on=KEYS, how="left")
    else:
        # Day 0 with no pre start activity for anyone would land here.
        agg = pd.DataFrame(columns=KEYS)

    f = pop.merge(agg, on=KEYS, how="left")

    for c in [
        "clicks_total",
        "events_total",
        "active_days",
        "clicks_last7",
        "clicks_last14",
        "clicks_prestart",
    ]:
        if c not in f.columns:
            f[c] = 0
        f[c] = f[c].fillna(0)

    if "last_active_day" not in f.columns:
        f["last_active_day"] = np.nan

    f["ever_active"] = (f["clicks_total"] > 0).astype(int)
    f["days_since_active"] = np.where(
        f["last_active_day"].notna(), D - f["last_active_day"], NEVER_ACTIVE
    )
    f["clicks_per_active_day"] = np.where(
        f["active_days"] > 0, f["clicks_total"] / f["active_days"], 0.0
    )
    f["registered_early_days"] = -f["date_registration"].fillna(0)

    # --- Guard 2. Assessments submitted strictly before D. ------------------
    sub = sa[sa["date_submitted"] < D]
    if len(sub):
        assert sub["date_submitted"].max() < D, f"Assessment leak at day {D}"
        a = (
            sub.groupby(KEYS, observed=True)
            .agg(
                n_submitted=("id_assessment", "size"),
                score_mean=("score", "mean"),
                score_min=("score", "min"),
            )
            .reset_index()
        )
        f = f.merge(a, on=KEYS, how="left")
    else:
        f["n_submitted"] = 0
        f["score_mean"] = np.nan
        f["score_min"] = np.nan

    f["n_submitted"] = f["n_submitted"].fillna(0)
    f["submitted_any"] = (f["n_submitted"] > 0).astype(int)

    cols = (
        KEYS
        + STATIC
        + [
            "clicks_total",
            "events_total",
            "active_days",
            "clicks_last7",
            "clicks_last14",
            "clicks_prestart",
            "clicks_per_active_day",
            "days_since_active",
            "ever_active",
            "registered_early_days",
            "n_submitted",
            "submitted_any",
            "score_mean",
            "score_min",
            "fold",
            "outcome",
        ]
    )
    f = f[cols]
    f.to_parquet(PROC / f"features_d{D}.parquet", index=False)

    n = len(f)
    n_out = int(f["outcome"].sum())
    rate = n_out / n * 100
    active_share = f["ever_active"].mean() * 100
    sub_share = f["submitted_any"].mean() * 100

    slice_stats[str(D)] = {
        "rows": n,
        "outcome_positive": n_out,
        "outcome_rate_pct": round(rate, 4),
        "ever_active_pct": round(active_share, 4),
        "submitted_any_pct": round(sub_share, 4),
        "score_mean_missing_pct": round(f["score_mean"].isna().mean() * 100, 4),
    }

w("## Slice summary")
w()
w("| Day | Rows | Withdraw at or after D | Rate | Any activity before D | Any assessment before D |")
w("|---:|---:|---:|---:|---:|---:|")
for D in DECISION_DAYS:
    s = slice_stats[str(D)]
    w(
        f"| {D} | {s['rows']:,} | {s['outcome_positive']:,} | {s['outcome_rate_pct']:.2f}% | "
        f"{s['ever_active_pct']:.1f}% | {s['submitted_any_pct']:.1f}% |"
    )
w()
w(
    "The base rate falls as D increases. This is not the model getting easier. Students "
    "who were going to leave early have already left, so the remaining population is "
    "systematically more committed. Any comparison of model quality across decision "
    "points must account for the base rate shift, and calibration is reported per slice "
    "rather than pooled."
)
w()

w("## Features")
w()
w("| Feature | Available at | Definition |")
w("|---|---|---|")
w("| gender, region, highest_education, imd_band, age_band | day 0 | Static, from registration |")
w("| num_of_prev_attempts, studied_credits, disability | day 0 | Static |")
w("| registered_early_days | day 0 | Days before module start that registration occurred |")
w("| clicks_prestart | day 0 | Clicks recorded before day 0 |")
w("| clicks_total, events_total, active_days | D > 0 | Cumulative over days < D |")
w("| clicks_last7, clicks_last14 | D > 0 | Recent window immediately before D |")
w("| clicks_per_active_day | D > 0 | Intensity when present |")
w("| days_since_active | D > 0 | D minus last active day, 999 if never |")
w("| ever_active | D > 0 | Any recorded click before D |")
w("| n_submitted, submitted_any, score_mean, score_min | D > 0 | Assessments submitted before D |")
w()
w(
    "At day 0 the only behavioural signal is pre start clicking and how early the student "
    "registered. Everything else is demographic. That is the honest information set at "
    "the one decision point where every withdrawal is still reachable."
)
w()

stats["slices"] = slice_stats
stats["decision_days"] = DECISION_DAYS
stats["never_active_sentinel"] = NEVER_ACTIVE

(DOCS / "03_features.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "feature_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
for D in DECISION_DAYS:
    print(f"Wrote data/processed/features_d{D}.parquet")
print("Wrote docs/03_features.md")
print("Wrote cache/feature_stats.json")
