"""
04_risk_model.py

Fits the risk model. This is the conventional half of the project: it builds the list
that institutions already build. It is not the finding. It exists so that the effect
based ranking has something real to be compared against.

Two commitments, made before results are seen.

  Baselines, pre registered. A model is reported as useful only against these:
    B1. Prevalence. Predict the training fold base rate for everyone. Any model that
        does not beat this is worthless.
    B2. Single feature logistic on log1p(clicks_total), or log1p(clicks_prestart) at
        day 0. A model that does not beat one obvious feature is not worth its
        complexity.

  Calibration before discrimination. The allocation problem needs probabilities that
  mean what they say, because expected outcomes averted is a sum of probabilities, not
  a ranking. AUC is reported but is secondary. Brier score and calibration error lead.

Evaluation uses the student level folds fixed in 02_cohort.py. They are never reshuffled.

What this script does NOT do, stated so it is not mistaken for done:
  - No leave one cohort out evaluation. Withdrawal rates range from 6.93% to 46.38%
    across module presentations, so within fold performance overstates what a model
    would achieve on a cohort it has never seen. That test belongs in a later script.
  - No hyperparameter search. Defaults are used deliberately. Tuning against these
    folds would contaminate the same folds the allocation comparison relies on.

Usage:
    python 04_risk_model.py

Reads:
    data/processed/features_d{D}.parquet

Writes:
    data/processed/risk_oof_d{D}.parquet   out of fold predictions, one row per student
    docs/04_risk_model.md
    cache/risk_stats.json
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import brier_score_loss, roc_auc_score
from sklearn.preprocessing import OrdinalEncoder

warnings.filterwarnings("ignore", category=UserWarning)

PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

DECISION_DAYS = [0, 28, 56, 84]
N_BINS = 10
SEED = 20260821

CATEGORICAL = [
    "code_module",
    "code_presentation",
    "gender",
    "region",
    "highest_education",
    "imd_band",
    "age_band",
    "disability",
]

DROP = ["id_student", "fold", "outcome"]

stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


def ece(y, p, n_bins=N_BINS):
    """Expected calibration error. Mean absolute gap between predicted and observed,
    weighted by bin size. Equal count bins, because equal width bins are mostly empty
    at the top when the base rate is low."""
    order = np.argsort(p)
    y, p = np.asarray(y)[order], np.asarray(p)[order]
    bins = np.array_split(np.arange(len(y)), n_bins)
    total, err = 0, 0.0
    for b in bins:
        if len(b) == 0:
            continue
        err += len(b) * abs(p[b].mean() - y[b].mean())
        total += len(b)
    return err / total if total else np.nan


def calibration_table(y, p, n_bins=N_BINS):
    order = np.argsort(p)
    y, p = np.asarray(y)[order], np.asarray(p)[order]
    rows = []
    for i, b in enumerate(np.array_split(np.arange(len(y)), n_bins)):
        if len(b) == 0:
            continue
        rows.append(
            {
                "bin": i + 1,
                "n": len(b),
                "pred_mean": float(p[b].mean()),
                "obs_rate": float(y[b].mean()),
            }
        )
    return rows


w("# 04. Risk model")
w()
w("Generated by `04_risk_model.py`. Do not edit by hand.")
w()
w(
    "This is the ranking institutions already produce. It is the comparison object for "
    "the effect based ranking, not a result in itself."
)
w()
w("## Pre registered baselines")
w()
w("| Baseline | Definition |")
w("|---|---|")
w("| B1 Prevalence | Training fold base rate predicted for everyone |")
w("| B2 One feature | Logistic on log1p(clicks_total), or log1p(clicks_prestart) at day 0 |")
w()
w(
    "A model is reported as useful only if it beats both on Brier score. Calibration is "
    "reported before discrimination because the allocation step sums probabilities and "
    "needs them to be true, not merely ordered."
)
w()

results = {}

for D in DECISION_DAYS:
    df = pd.read_parquet(PROC / f"features_d{D}.parquet")

    y = df["outcome"].to_numpy()
    folds = df["fold"].to_numpy()

    feat_cols = [c for c in df.columns if c not in DROP]
    cats = [c for c in CATEGORICAL if c in feat_cols]
    nums = [c for c in feat_cols if c not in cats]

    X = df[feat_cols].copy()
    for c in cats:
        X[c] = X[c].astype("object").where(X[c].notna(), "__missing__")

    enc = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
    X_enc = X.copy()
    if cats:
        X_enc[cats] = enc.fit_transform(X[cats])
    X_enc = X_enc.astype(float)

    cat_mask = [c in cats for c in X_enc.columns]

    # B2 uses clicks_total rather than days_since_active. days_since_active carries a
    # sentinel of 999 for students never active, which puts roughly 3% of the population
    # 180 standard deviations from the rest. After standardisation every active student
    # collapses to a sliver near zero and the logistic cannot separate them, so the
    # baseline silently degenerates to the base rate. log1p(clicks_total) has no sentinel
    # and no scale pathology.
    single = "clicks_prestart" if D == 0 else "clicks_total"

    oof_model = np.zeros(len(df))
    oof_b1 = np.zeros(len(df))
    oof_b2 = np.zeros(len(df))
    per_fold = []

    for f in sorted(np.unique(folds)):
        tr, te = folds != f, folds == f

        # B1. Prevalence.
        oof_b1[te] = y[tr].mean()

        # B2. One feature logistic.
        s_tr = df.loc[tr, single].to_numpy().reshape(-1, 1)
        s_te = df.loc[te, single].to_numpy().reshape(-1, 1)
        s_tr, s_te = np.log1p(s_tr), np.log1p(s_te)
        mu, sd = s_tr.mean(), s_tr.std() or 1.0
        lr = LogisticRegression(max_iter=1000)
        lr.fit((s_tr - mu) / sd, y[tr])
        oof_b2[te] = lr.predict_proba((s_te - mu) / sd)[:, 1]

        # Model.
        clf = HistGradientBoostingClassifier(
            categorical_features=cat_mask,
            random_state=SEED,
            early_stopping=True,
            validation_fraction=0.15,
        )
        clf.fit(X_enc[tr], y[tr])
        p = clf.predict_proba(X_enc[te])[:, 1]
        oof_model[te] = p

        per_fold.append(
            {
                "fold": int(f),
                "n": int(te.sum()),
                "brier": float(brier_score_loss(y[te], p)),
                "auc": float(roc_auc_score(y[te], p)),
                "ece": float(ece(y[te], p)),
            }
        )

    briers = np.array([r["brier"] for r in per_fold])
    aucs = np.array([r["auc"] for r in per_fold])

    res = {
        "n": int(len(df)),
        "base_rate_pct": float(y.mean() * 100),
        "single_feature": single,
        "model": {
            "brier": float(brier_score_loss(y, oof_model)),
            "auc": float(roc_auc_score(y, oof_model)),
            "ece": float(ece(y, oof_model)),
            "brier_fold_sd": float(briers.std(ddof=1)),
            "auc_fold_sd": float(aucs.std(ddof=1)),
        },
        "b1_prevalence": {"brier": float(brier_score_loss(y, oof_b1))},
        "b2_single_feature": {
            "brier": float(brier_score_loss(y, oof_b2)),
            "auc": float(roc_auc_score(y, oof_b2)),
        },
        "per_fold": per_fold,
        "calibration": calibration_table(y, oof_model),
    }
    results[str(D)] = res

    out = df[["id_student", "code_module", "code_presentation", "fold", "outcome"]].copy()
    out["risk"] = oof_model
    out.to_parquet(PROC / f"risk_oof_d{D}.parquet", index=False)

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

w("## Results")
w()
w("| Day | N | Base rate | B1 Brier | B2 Brier | Model Brier | Model AUC | ECE |")
w("|---:|---:|---:|---:|---:|---:|---:|---:|")
for D in DECISION_DAYS:
    r = results[str(D)]
    w(
        f"| {D} | {r['n']:,} | {r['base_rate_pct']:.2f}% | "
        f"{r['b1_prevalence']['brier']:.4f} | {r['b2_single_feature']['brier']:.4f} | "
        f"{r['model']['brier']:.4f} | {r['model']['auc']:.3f} | {r['model']['ece']:.4f} |"
    )
w()

w("### Does the model beat its baselines?")
w()
w("| Day | Beats B1 | Beats B2 | Brier improvement over B1 |")
w("|---:|---|---|---:|")
for D in DECISION_DAYS:
    r = results[str(D)]
    m, b1, b2 = r["model"]["brier"], r["b1_prevalence"]["brier"], r["b2_single_feature"]["brier"]
    gain = (b1 - m) / b1 * 100
    w(f"| {D} | {'yes' if m < b1 else 'NO'} | {'yes' if m < b2 else 'NO'} | {gain:.1f}% |")
w()

w("### Fold to fold variance")
w()
w(
    "A single number hides how much of it is luck. Standard deviation across the five "
    "folds is reported so that later comparisons are not read as meaningful when they "
    "fall inside this range."
)
w()
w("| Day | Brier mean | Brier SD | AUC mean | AUC SD |")
w("|---:|---:|---:|---:|---:|")
for D in DECISION_DAYS:
    r = results[str(D)]
    bm = np.mean([f["brier"] for f in r["per_fold"]])
    am = np.mean([f["auc"] for f in r["per_fold"]])
    w(
        f"| {D} | {bm:.4f} | {r['model']['brier_fold_sd']:.4f} | "
        f"{am:.3f} | {r['model']['auc_fold_sd']:.3f} |"
    )
w()

w("### Calibration")
w()
w(
    "Equal count decile bins on out of fold predictions. If predicted and observed "
    "diverge, the probabilities cannot be summed to estimate outcomes averted, and the "
    "allocation comparison would be built on sand."
)
w()
for D in DECISION_DAYS:
    r = results[str(D)]
    w(f"**Day {D}**")
    w()
    w("| Bin | N | Predicted | Observed | Gap |")
    w("|---:|---:|---:|---:|---:|")
    for b in r["calibration"]:
        gap = b["obs_rate"] - b["pred_mean"]
        w(
            f"| {b['bin']} | {b['n']:,} | {b['pred_mean']:.4f} | "
            f"{b['obs_rate']:.4f} | {gap:+.4f} |"
        )
    w()

w("## Reading these numbers")
w()
w(
    "AUC rises with the decision point because later slices carry more behavioural "
    "signal. It does not follow that later allocation is better. The addressable "
    "population shrinks at exactly the same time: day 0 reaches 100% of withdrawals, "
    "day 84 reaches 43.4%. Whether a weaker model applied to everyone beats a stronger "
    "model applied to less than half is the question the allocation script answers, and "
    "nothing here settles it."
)
w()

stats["results"] = results
stats["seed"] = SEED

(DOCS / "04_risk_model.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "risk_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
for D in DECISION_DAYS:
    print(f"Wrote data/processed/risk_oof_d{D}.parquet")
print("Wrote docs/04_risk_model.md")
print("Wrote cache/risk_stats.json")
