"""
05_cohort_validation.py

Tests whether the risk model in 04 knows anything about students, or mostly knows which
cohort they are in.

Withdrawal rates run from 6.93% to 46.38% across module presentations. `code_module` and
`code_presentation` are both model features. A model can therefore score well by learning
that module CCC loses a lot of students and module GGG does not, without distinguishing
one CCC student from another. Five fold cross validation cannot detect this, because
every fold contains every cohort.

Two tests.

  Test 1. Leave one module out. Train on six modules, predict the seventh. This is the
          deployment condition an institution actually faces: a model built on history
          applied to a population it has not seen. If performance collapses here, the
          numbers in 04 describe interpolation within known cohorts, not generalisation.

  Test 2. Cohort identifier ablation. Refit with `code_module` and `code_presentation`
          removed, everything else unchanged. The gap between the two is the share of
          performance attributable to knowing the cohort rather than the student.

Neither test is decisive alone. Together they bound the claim.

Usage:
    python 05_cohort_validation.py

Reads:
    data/processed/features_d{D}.parquet

Writes:
    docs/05_cohort_validation.md
    cache/cohort_validation_stats.json
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import brier_score_loss, roc_auc_score
from sklearn.preprocessing import OrdinalEncoder

warnings.filterwarnings("ignore", category=UserWarning)

PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

DECISION_DAYS = [0, 28, 56, 84]
SEED = 20260821

CATEGORICAL = [
    "code_module",
    "code_presentation",
    "gender",
    "region",
    "highest_education",
    "imd_band",
    "age_band",
    "disability",
]

COHORT_IDS = ["code_module", "code_presentation"]
DROP = ["id_student", "fold", "outcome"]

stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


def prep(df, feat_cols):
    cats = [c for c in CATEGORICAL if c in feat_cols]
    X = df[feat_cols].copy()
    for c in cats:
        X[c] = X[c].astype("object").where(X[c].notna(), "__missing__")
    if cats:
        enc = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
        X[cats] = enc.fit_transform(X[cats])
    X = X.astype(float)
    return X, [c in cats for c in X.columns]


def fit_predict(Xtr, ytr, Xte, cat_mask):
    clf = HistGradientBoostingClassifier(
        categorical_features=cat_mask,
        random_state=SEED,
        early_stopping=True,
        validation_fraction=0.15,
    )
    clf.fit(Xtr, ytr)
    return clf.predict_proba(Xte)[:, 1]


w("# 05. Cohort validation")
w()
w("Generated by `05_cohort_validation.py`. Do not edit by hand.")
w()
w(
    "The cross validated figures in `04_risk_model.md` are computed on folds that all "
    "contain all cohorts. This document asks whether those figures survive when the "
    "model meets a cohort it has never seen, and how much of the performance comes from "
    "knowing the cohort rather than the student."
)
w()

results = {}

for D in DECISION_DAYS:
    df = pd.read_parquet(PROC / f"features_d{D}.parquet")
    y = df["outcome"].to_numpy()
    feat_all = [c for c in df.columns if c not in DROP]
    feat_noid = [c for c in feat_all if c not in COHORT_IDS]

    day_res = {}

    # --- Test 2 first. Pooled fold CV with and without cohort identifiers. ----
    for label, cols in (("with_ids", feat_all), ("without_ids", feat_noid)):
        X, mask = prep(df, cols)
        oof = np.zeros(len(df))
        for f in sorted(df["fold"].unique()):
            tr, te = (df["fold"] != f).to_numpy(), (df["fold"] == f).to_numpy()
            oof[te] = fit_predict(X[tr], y[tr], X[te], mask)
        day_res[label] = {
            "auc": float(roc_auc_score(y, oof)),
            "brier": float(brier_score_loss(y, oof)),
        }

    # --- Test 1. Leave one module out, without cohort identifiers. -----------
    # Identifiers are excluded here because a held out module's identifier is a value
    # the model has never seen, which makes the comparison incoherent rather than hard.
    X, mask = prep(df, feat_noid)
    modules = sorted(df["code_module"].unique())
    loco = []
    for m in modules:
        tr = (df["code_module"] != m).to_numpy()
        te = ~tr
        if y[te].sum() < 10 or y[te].sum() == te.sum():
            continue
        p = fit_predict(X[tr], y[tr], X[te], mask)
        loco.append(
            {
                "module": str(m),
                "n": int(te.sum()),
                "base_rate_pct": float(y[te].mean() * 100),
                "auc": float(roc_auc_score(y[te], p)),
                "brier": float(brier_score_loss(y[te], p)),
                "pred_mean": float(p.mean()),
            }
        )
    day_res["loco"] = loco
    day_res["loco_auc_mean"] = float(np.mean([r["auc"] for r in loco]))
    day_res["loco_auc_min"] = float(np.min([r["auc"] for r in loco]))
    day_res["loco_auc_max"] = float(np.max([r["auc"] for r in loco]))

    results[str(D)] = day_res

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

w("## Test 2. How much is cohort knowledge?")
w()
w("| Day | AUC with cohort ids | AUC without | Difference |")
w("|---:|---:|---:|---:|")
for D in DECISION_DAYS:
    r = results[str(D)]
    a, b = r["with_ids"]["auc"], r["without_ids"]["auc"]
    w(f"| {D} | {a:.3f} | {b:.3f} | {a - b:+.3f} |")
w()
w(
    "A large positive difference means the model is leaning on cohort base rates. A "
    "difference near zero means the cohort identifiers were not carrying the "
    "performance, and the individual level features were."
)
w()

w("## Test 1. Leave one module out")
w()
w(
    "Cohort identifiers excluded. Each row is a module the model never saw during "
    "training. Fold standard deviation in `04_risk_model.md` was 0.007 to 0.014, so "
    "spread beyond that range here is real, not sampling noise."
)
w()
for D in DECISION_DAYS:
    r = results[str(D)]
    w(f"**Day {D}** (pooled AUC without ids: {r['without_ids']['auc']:.3f})")
    w()
    w("| Held out module | N | Base rate | Predicted mean | AUC | Brier |")
    w("|---|---:|---:|---:|---:|---:|")
    for m in r["loco"]:
        w(
            f"| {m['module']} | {m['n']:,} | {m['base_rate_pct']:.2f}% | "
            f"{m['pred_mean'] * 100:.2f}% | {m['auc']:.3f} | {m['brier']:.4f} |"
        )
    w()
    w(
        f"Range: {r['loco_auc_min']:.3f} to {r['loco_auc_max']:.3f}, "
        f"mean {r['loco_auc_mean']:.3f}."
    )
    w()

w("## What this bounds")
w()
w(
    "The gap between predicted mean and base rate in the leave one module out table is "
    "the calibration failure that matters most. A model trained on six modules and "
    "applied to a seventh with a very different withdrawal rate will be miscalibrated "
    "in level even if it ranks well. Ranking survives transfer better than calibration "
    "does, and the allocation step needs both: ranking to choose who, calibration to "
    "estimate how many outcomes are averted."
)
w()
w(
    "Any claim about day 0 performance in public material must cite the leave one module "
    "out figure, not the pooled cross validated figure, because the pooled figure "
    "describes a condition no deploying institution is in."
)
w()

stats["results"] = results
stats["seed"] = SEED

(DOCS / "05_cohort_validation.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "cohort_validation_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print("Wrote docs/05_cohort_validation.md")
print("Wrote cache/cohort_validation_stats.json")
