"""
06_allocation.py

The comparison the project exists to make.

Given a capacity k, two ways to choose who receives an intervention:

    R_k   the k people with the highest predicted risk
    E_k   the k people with the highest predicted marginal effect

This script measures how far apart those two sets are, and what the difference costs.

WHAT THIS IS NOT
================
This is not an estimate of treatment effects. No randomised experiment is in hand for
this population, so no effect is identified here. What follows is a decision analysis:
given a stated efficacy structure, which ranking maximises expected outcomes averted,
and over what range of that structure does the answer hold.

The efficacy family, one parameter:

    tau(r) = c * r * (1 - r)^gamma

    gamma = 0   effect proportional to baseline risk. Monotone increasing in r, so
                risk ranking is optimal and the project's thesis is FALSE here.
    gamma > 0   effect peaks at r = 1 / (1 + gamma) and falls above it. The intervention
                saturates: people at very high risk are leaving for reasons it does not
                touch.

c is solved per cohort so that the average effect among the treated is held fixed at
ATE_TARGET across every gamma. Without that normalisation, changing gamma would change
both the shape and the magnitude of efficacy, and the comparison would be meaningless.

A consequence worth stating plainly: tau is a deterministic function of r here, so the
effect ranking is a reordering of the same risk scores rather than independent
information. Real treatment effect heterogeneity depends on covariates beyond baseline
risk, and estimating that is exactly what the missing experiment would supply. This
analysis therefore bounds the divergence attributable to efficacy SHAPE alone. Genuine
covariate driven heterogeneity would add to it, not subtract.

NOISE FLOOR
===========
An overlap of 0.4 means nothing on its own if two refits of the risk model on resampled
data also overlap at 0.4. The script therefore refits the risk model on bootstrap
resamples and reports the overlap between two independent risk rankings at the same
capacity. Any divergence inside that band is estimation noise, not a finding. This test
is pre committed and is reported whether or not it is passed.

Analysis runs WITHIN cohort. 05_cohort_validation.md showed the model does not transfer
across modules, so a pooled allocation would be built on predictions known to be
miscalibrated out of sample.

Usage:
    python 06_allocation.py

Reads:
    data/processed/risk_oof_d{D}.parquet
    data/processed/features_d{D}.parquet

Writes:
    docs/06_allocation.md
    cache/allocation_stats.json
    data/processed/allocation_curves.parquet   for the interactive console later
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.preprocessing import OrdinalEncoder

warnings.filterwarnings("ignore", category=UserWarning)

PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

DECISION_DAYS = [0, 28, 56, 84]
GAMMAS = [0.0, 0.5, 1.0, 1.5, 2.0, 3.0]
CAPACITY_PCT = [0.01, 0.02, 0.05, 0.10, 0.20]
ATE_TARGET = 0.05  # 5 percentage point average reduction among the treated
MIN_COHORT = 500
N_BOOTSTRAP = 10
SEED = 20260821

CATEGORICAL = [
    "gender",
    "region",
    "highest_education",
    "imd_band",
    "age_band",
    "disability",
]
DROP = ["id_student", "fold", "outcome", "code_module", "code_presentation"]

rng = np.random.default_rng(SEED)
stats = {}
lines = []
curves = []


def w(s=""):
    lines.append(s)
    print(s)


def tau_of_r(r, gamma, ate_target):
    """Effect as a function of baseline risk, normalised to a fixed mean effect."""
    shape = r * (1.0 - r) ** gamma
    m = shape.mean()
    if m <= 0:
        return np.zeros_like(shape)
    return shape * (ate_target / m)


def topk_mask(x, k):
    idx = np.argsort(-x, kind="stable")[:k]
    m = np.zeros(len(x), dtype=bool)
    m[idx] = True
    return m


w("# 06. Allocation")
w()
w("Generated by `06_allocation.py`. Do not edit by hand.")
w()
w("## What this measures, and what it does not")
w()
w(
    "No randomised experiment is available for this population. Treatment effects are "
    "not estimated here. This is a decision analysis: given a stated efficacy structure, "
    "which ranking maximises expected outcomes averted, and over what range of that "
    "structure does the answer hold."
)
w()
w("Efficacy family, one parameter:")
w()
w("```")
w("tau(r) = c * r * (1 - r)^gamma")
w("```")
w()
w(
    "`gamma = 0` makes effect proportional to risk. Effect is then monotone increasing "
    "in risk, risk ranking is optimal, and the thesis is false. `gamma > 0` makes effect "
    "peak at `r = 1 / (1 + gamma)` and decline above it. `c` is solved per cohort so the "
    "mean effect among the treated equals "
    f"{ATE_TARGET:.0%} at every gamma, holding total efficacy fixed while shape varies."
)
w()
w(
    "Because tau is a function of r alone, the effect ranking here is a reordering of the "
    "same scores. This bounds the divergence attributable to efficacy shape only. Real "
    "heterogeneity depends on covariates beyond baseline risk, and estimating it is what "
    "the missing experiment would supply. That component would add to the divergence "
    "measured here, not reduce it."
)
w()
w(f"Analysis runs within cohort, minimum {MIN_COHORT:,} registrations.")
w()

# ---------------------------------------------------------------------------
# Noise floor
# ---------------------------------------------------------------------------

w("## Noise floor")
w()
w(
    "Two risk models fit on independent bootstrap resamples of the same cohort produce "
    "two risk rankings. Their overlap at capacity k is the level below which no "
    "divergence can be called a finding."
)
w()

noise = {}

for D in DECISION_DAYS:
    feat = pd.read_parquet(PROC / f"features_d{D}.parquet")
    cohorts = (
        feat.groupby(["code_module", "code_presentation"]).size().loc[lambda s: s >= MIN_COHORT]
    )
    # One representative cohort, the largest, to keep runtime honest.
    mp = cohorts.idxmax()
    sub = feat[
        (feat["code_module"] == mp[0]) & (feat["code_presentation"] == mp[1])
    ].reset_index(drop=True)

    cols = [c for c in sub.columns if c not in DROP]
    cats = [c for c in CATEGORICAL if c in cols]
    X = sub[cols].copy()
    for c in cats:
        X[c] = X[c].astype("object").where(X[c].notna(), "__missing__")
    if cats:
        X[cats] = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1).fit_transform(
            X[cats]
        )
    X = X.astype(float)
    mask = [c in cats for c in X.columns]
    y = sub["outcome"].to_numpy()
    n = len(sub)

    per_cap = {f"{p:.2f}": [] for p in CAPACITY_PCT}
    for _ in range(N_BOOTSTRAP):
        preds = []
        for _ in range(2):
            idx = rng.integers(0, n, n)
            clf = HistGradientBoostingClassifier(
                categorical_features=mask, random_state=int(rng.integers(1e6)), early_stopping=True,
                validation_fraction=0.15,
            )
            clf.fit(X.iloc[idx], y[idx])
            preds.append(clf.predict_proba(X)[:, 1])
        for p in CAPACITY_PCT:
            k = max(1, int(round(p * n)))
            o = (topk_mask(preds[0], k) & topk_mask(preds[1], k)).sum() / k
            per_cap[f"{p:.2f}"].append(o)

    noise[str(D)] = {
        "cohort": f"{mp[0]} {mp[1]}",
        "n": int(n),
        "overlap": {c: {"mean": float(np.mean(v)), "sd": float(np.std(v, ddof=1))} for c, v in per_cap.items()},
    }

w("| Day | Cohort | N | " + " | ".join(f"{p:.0%}" for p in CAPACITY_PCT) + " |")
w("|---:|---|---:|" + "---:|" * len(CAPACITY_PCT))
for D in DECISION_DAYS:
    nz = noise[str(D)]
    cells = " | ".join(
        f"{nz['overlap'][f'{p:.2f}']['mean']:.2f}" for p in CAPACITY_PCT
    )
    w(f"| {D} | {nz['cohort']} | {nz['n']:,} | {cells} |")
w()
w(
    "Two refits of the same model on the same cohort agree only this well. Risk versus "
    "effect overlap must fall clearly below these values to mean anything."
)
w()

stats["noise_floor"] = noise

# ---------------------------------------------------------------------------
# Allocation comparison
# ---------------------------------------------------------------------------

for D in DECISION_DAYS:
    oof = pd.read_parquet(PROC / f"risk_oof_d{D}.parquet")
    sizes = oof.groupby(["code_module", "code_presentation"]).size()
    keep = sizes[sizes >= MIN_COHORT].index

    for mp in keep:
        sub = oof[
            (oof["code_module"] == mp[0]) & (oof["code_presentation"] == mp[1])
        ]
        r = sub["risk"].to_numpy()
        n = len(r)

        for g in GAMMAS:
            tau = tau_of_r(r, g, ATE_TARGET)
            for p in CAPACITY_PCT:
                k = max(1, int(round(p * n)))
                mr, me = topk_mask(r, k), topk_mask(tau, k)
                v_r, v_e = tau[mr].sum(), tau[me].sum()
                curves.append(
                    {
                        "day": D,
                        "module": mp[0],
                        "presentation": mp[1],
                        "n": n,
                        "gamma": g,
                        "capacity_pct": p,
                        "k": k,
                        "overlap": float((mr & me).sum() / k),
                        "value_risk": float(v_r),
                        "value_effect": float(v_e),
                        "value_gap_pct": float((v_e - v_r) / v_e * 100) if v_e > 0 else 0.0,
                    }
                )

cur = pd.DataFrame(curves)
cur.to_parquet(PROC / "allocation_curves.parquet", index=False)

# ---------------------------------------------------------------------------
# Headline tables
# ---------------------------------------------------------------------------

w("## Overlap between the two rankings")
w()
w("Mean across cohorts, weighted equally. Rows are the efficacy shape, columns capacity.")
w()

for D in DECISION_DAYS:
    d = cur[cur["day"] == D]
    w(f"**Day {D}**")
    w()
    w("| gamma | peak risk | " + " | ".join(f"{p:.0%}" for p in CAPACITY_PCT) + " |")
    w("|---:|---:|" + "---:|" * len(CAPACITY_PCT))
    for g in GAMMAS:
        peak = 1.0 / (1.0 + g)
        cells = " | ".join(
            f"{d[(d['gamma'] == g) & (d['capacity_pct'] == p)]['overlap'].mean():.2f}"
            for p in CAPACITY_PCT
        )
        w(f"| {g:.1f} | {peak:.2f} | {cells} |")
    w()

w("## Cost of ranking by risk")
w()
w(
    "Percentage of achievable outcomes averted that risk ranking leaves on the table. "
    "This is the number that decides whether the overlap gap matters. A low overlap with "
    "a negligible value gap is not a reason to change anything."
)
w()

for D in DECISION_DAYS:
    d = cur[cur["day"] == D]
    w(f"**Day {D}**")
    w()
    w("| gamma | " + " | ".join(f"{p:.0%}" for p in CAPACITY_PCT) + " |")
    w("|---:|" + "---:|" * len(CAPACITY_PCT))
    for g in GAMMAS:
        cells = " | ".join(
            f"{d[(d['gamma'] == g) & (d['capacity_pct'] == p)]['value_gap_pct'].mean():.1f}%"
            for p in CAPACITY_PCT
        )
        w(f"| {g:.1f} | {cells} |")
    w()

w("## Reading this")
w()
w(
    "At gamma = 0 the two rankings are identical by construction and the value gap is "
    "zero. That row is the control. Everything else is measured against it."
)
w()
w(
    "The question a director faces is not which ranking is better in the abstract. It is "
    "whether their intervention saturates, and at what level of risk. That is an "
    "empirical question about their own programme which this analysis cannot answer and "
    "which almost no institution has measured."
)
w()

stats["gammas"] = GAMMAS
stats["capacity_pct"] = CAPACITY_PCT
stats["ate_target"] = ATE_TARGET
stats["min_cohort"] = MIN_COHORT
stats["n_bootstrap"] = N_BOOTSTRAP
stats["seed"] = SEED

(DOCS / "06_allocation.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "allocation_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print(f"Wrote data/processed/allocation_curves.parquet  ({len(cur):,} rows)")
print("Wrote docs/06_allocation.md")
print("Wrote cache/allocation_stats.json")
