"""
06_allocation.py  (version 2)

The comparison the project exists to make, measured against a valid noise floor.

WHY THIS WAS REWRITTEN
======================
Version 1 measured its noise floor by fitting models on bootstrap resamples and then
predicting on rows those models had trained on. `07_stability.md` showed that inflated
AUC to 0.93 against an honest 0.70, so the floor was memorisation noise rather than
ranking instability. Every conclusion version 1 drew about which divergences survived
was therefore unsupported.

Two further changes follow from `07_stability.md`:

  Estimator. Logistic regression replaces gradient boosting. It was the most stable of
  the three tested, at equal or better AUC out of sample. Since the object of study is a
  ranking, an estimator that cannot reproduce its own ranking is the wrong instrument.

  Measurement. Divergence and noise floor are now computed on the same students, in the
  same replication, at the same capacity. Version 1 compared numbers produced by
  different procedures on different samples, which made the comparison unsound even
  before the in sample error.

THE DESIGN
==========
For each cohort and each replication, the cohort is split three ways at student level:

    part A   trains model A
    part B   trains model B
    part C   evaluation, seen by neither

Both models rank part C by predicted risk. Then, on part C:

    noise floor   overlap between model A's top k and model B's top k.
                  Two honest analysts with different halves of the history.

    divergence    overlap between model A's risk top k and the effect ranking
                  derived from model A's own predictions.

Divergence below the noise floor means the two rankings disagree by more than two
independent risk models disagree with each other. Divergence above it means the gap is
smaller than the instability of the thing being ranked, and nothing can be concluded.

EFFICACY
========
No randomised experiment is available, so treatment effects are not estimated. Efficacy
is a one parameter family:

    tau(r) = c * r * (1 - r)^gamma

gamma = 0 makes effect proportional to risk, the two rankings identical, and the thesis
false. gamma > 0 puts the peak at r = 1 / (1 + gamma). c is solved per cohort so mean
effect among the treated is held at ATE_TARGET across every gamma, so that gamma varies
shape without varying magnitude.

tau is a function of r alone, so this bounds the divergence attributable to efficacy
shape only. Covariate driven heterogeneity, which the missing experiment would supply,
would add to it.

Usage:
    python 06_allocation.py

Reads:
    data/processed/features_d{D}.parquet

Writes:
    docs/06_allocation.md
    cache/allocation_stats.json
    data/processed/allocation_curves.parquet
"""

import hashlib
import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

DECISION_DAYS = [0, 28, 56, 84]
GAMMAS = [0.0, 0.5, 1.0, 1.5, 2.0, 3.0]
CAPACITY_PCT = [0.01, 0.02, 0.05, 0.10, 0.20]
ATE_TARGET = 0.05
MIN_COHORT = 1500
N_REPLICATIONS = 10
SEED = 20260821

CATEGORICAL = ["gender", "region", "highest_education", "imd_band", "age_band", "disability"]
DROP = ["id_student", "fold", "outcome", "code_module", "code_presentation"]

def seed_for(*parts):
    """Deterministic seed from labels. Independent of loop order, so figures reproduce
    exactly on rerun and do not shift when a cohort or day is added or removed."""
    h = hashlib.sha256("|".join(str(p) for p in parts).encode()).digest()
    return int.from_bytes(h[:8], "big")


stats = {}
lines = []
rows = []


def w(s=""):
    lines.append(s)
    print(s)


def topk(x, k):
    idx = np.argsort(-x, kind="stable")[:k]
    m = np.zeros(len(x), dtype=bool)
    m[idx] = True
    return m


def tau_of_r(r, gamma, ate):
    shape = r * (1.0 - r) ** gamma
    m = shape.mean()
    return shape * (ate / m) if m > 0 else np.zeros_like(shape)


def fit(Xtr, ytr, Xte, cats, nums):
    pre = ColumnTransformer(
        [
            ("cat", OneHotEncoder(handle_unknown="ignore", min_frequency=20), cats),
            ("num", make_pipeline(SimpleImputer(strategy="median"), StandardScaler()), nums),
        ]
    )
    pipe = make_pipeline(pre, LogisticRegression(max_iter=2000))
    pipe.fit(Xtr, ytr)
    return pipe.predict_proba(Xte)[:, 1]


w("# 06. Allocation")
w()
w("Generated by `06_allocation.py`. Do not edit by hand.")
w()
w("## Correction")
w()
w(
    "Version 1 of this analysis measured its noise floor on rows the models had trained "
    "on. `07_stability.md` showed that inflated AUC to 0.93 against an honest 0.70, so "
    "the floor was memorisation noise. Every conclusion version 1 drew about which "
    "divergences survived was unsupported and is replaced here."
)
w()
w(
    "Two changes follow. Logistic regression replaces gradient boosting, because "
    "`07_stability.md` found it the most stable of three estimators at equal or better "
    "out of sample AUC, and a ranking study needs an estimator that can reproduce its "
    "own ranking. And divergence and noise floor are now measured on the same students, "
    "in the same replication, at the same capacity."
)
w()
w("## Design")
w()
w(
    "Each cohort is split three ways at student level. Model A trains on part A, model B "
    "on part B, both rank part C. The noise floor is the overlap between A and B: two "
    "analysts with different halves of the same history. The divergence is the overlap "
    "between A's risk ranking and the effect ranking derived from A's own predictions."
)
w()
w("Efficacy is assumed, not estimated:")
w()
w("```")
w("tau(r) = c * r * (1 - r)^gamma")
w("```")
w()
w(
    f"`c` is solved per cohort so mean effect among the treated equals {ATE_TARGET:.0%} at "
    "every gamma. `gamma = 0` makes the rankings identical and is the control row. "
    "Because tau is a function of r alone, this bounds divergence from efficacy shape "
    "only; covariate driven heterogeneity would add to it."
)
w()
w(f"Cohorts with at least {MIN_COHORT:,} registrations. {N_REPLICATIONS} replications each.")
w()

cohort_list = {}

for D in DECISION_DAYS:
    feat = pd.read_parquet(PROC / f"features_d{D}.parquet")
    sizes = feat.groupby(["code_module", "code_presentation"]).size()
    keep = sizes[sizes >= MIN_COHORT].index
    cohort_list[D] = [f"{m} {p}" for m, p in keep]

    cols = [c for c in feat.columns if c not in DROP]
    cats = [c for c in CATEGORICAL if c in cols]
    nums = [c for c in cols if c not in cats]

    for mp in keep:
        sub = feat[
            (feat["code_module"] == mp[0]) & (feat["code_presentation"] == mp[1])
        ].reset_index(drop=True)
        X, y = sub[cols], sub["outcome"].to_numpy()
        n = len(sub)

        for rep in range(N_REPLICATIONS):
            rng = np.random.default_rng(seed_for(SEED, D, mp[0], mp[1], rep))
            perm = rng.permutation(n)
            a, b, c = np.array_split(perm, 3)
            yc = y[c]
            if not (0 < yc.sum() < len(yc)):
                continue

            ra = fit(X.iloc[a], y[a], X.iloc[c], cats, nums)
            rb = fit(X.iloc[b], y[b], X.iloc[c], cats, nums)
            auc = roc_auc_score(yc, ra)

            for p in CAPACITY_PCT:
                k = max(1, int(round(p * len(c))))
                mask_ra = topk(ra, k)
                floor = (mask_ra & topk(rb, k)).sum() / k

                for g in GAMMAS:
                    tau = tau_of_r(ra, g, ATE_TARGET)
                    mask_e = topk(tau, k)
                    v_r, v_e = tau[mask_ra].sum(), tau[mask_e].sum()
                    rows.append(
                        {
                            "day": D,
                            "cohort": f"{mp[0]} {mp[1]}",
                            "n_eval": len(c),
                            "capacity_pct": p,
                            "k": k,
                            "gamma": g,
                            "noise_floor": float(floor),
                            "overlap": float((mask_ra & mask_e).sum() / k),
                            "value_gap_pct": float((v_e - v_r) / v_e * 100) if v_e > 0 else 0.0,
                            "auc": float(auc),
                        }
                    )

cur = pd.DataFrame(rows)
cur.to_parquet(PROC / "allocation_curves.parquet", index=False)

# ---------------------------------------------------------------------------
# Noise floor
# ---------------------------------------------------------------------------

w("## Noise floor")
w()
w(
    "Overlap between two risk models trained on different halves of the same cohort, "
    "measured on students neither has seen. Mean across cohorts and replications."
)
w()
w("| Day | Cohorts | AUC | " + " | ".join(f"{p:.0%}" for p in CAPACITY_PCT) + " |")
w("|---:|---:|---:|" + "---:|" * len(CAPACITY_PCT))
floors = {}
for D in DECISION_DAYS:
    d = cur[cur["day"] == D]
    cells = []
    floors[D] = {}
    for p in CAPACITY_PCT:
        v = d[d["capacity_pct"] == p]["noise_floor"].mean()
        floors[D][p] = v
        cells.append(f"{v:.2f}")
    w(
        f"| {D} | {len(cohort_list[D])} | {d['auc'].mean():.3f} | " + " | ".join(cells) + " |"
    )
w()
w(
    "These are the values the risk versus effect overlap must fall below. AUC is "
    "reported alongside so that any inflation would be visible."
)
w()

# ---------------------------------------------------------------------------
# Divergence against the floor
# ---------------------------------------------------------------------------

w("## Divergence relative to the noise floor")
w()
w(
    "Each cell is the risk versus effect overlap minus the noise floor at the same day "
    "and capacity. Negative means the two rankings disagree by more than two independent "
    "risk models do, which is the only condition under which the divergence means "
    "anything. Positive means the gap is smaller than the instability of the ranking "
    "itself and nothing can be concluded."
)
w()

for D in DECISION_DAYS:
    d = cur[cur["day"] == D]
    w(f"**Day {D}**")
    w()
    w("| gamma | peak risk | " + " | ".join(f"{p:.0%}" for p in CAPACITY_PCT) + " |")
    w("|---:|---:|" + "---:|" * len(CAPACITY_PCT))
    for g in GAMMAS:
        cells = []
        for p in CAPACITY_PCT:
            s = d[(d["gamma"] == g) & (d["capacity_pct"] == p)]
            cells.append(f"{s['overlap'].mean() - floors[D][p]:+.2f}")
        w(f"| {g:.1f} | {1 / (1 + g):.2f} | " + " | ".join(cells) + " |")
    w()

# ---------------------------------------------------------------------------
# Value gap
# ---------------------------------------------------------------------------

w("## Cost of ranking by risk")
w()
w(
    "Percentage of achievable outcomes averted that risk ranking forgoes. Report this "
    "only for cells where the divergence clears the noise floor. Elsewhere it is a "
    "difference between two rankings that cannot be told apart."
)
w()

for D in DECISION_DAYS:
    d = cur[cur["day"] == D]
    w(f"**Day {D}**")
    w()
    w("| gamma | " + " | ".join(f"{p:.0%}" for p in CAPACITY_PCT) + " |")
    w("|---:|" + "---:|" * len(CAPACITY_PCT))
    for g in GAMMAS:
        cells = []
        for p in CAPACITY_PCT:
            s = d[(d["gamma"] == g) & (d["capacity_pct"] == p)]
            clears = s["overlap"].mean() < floors[D][p]
            v = s["value_gap_pct"].mean()
            cells.append(f"{v:.1f}%" if clears else f"({v:.1f}%)")
        w(f"| {g:.1f} | " + " | ".join(cells) + " |")
    w()
w("Values in parentheses did not clear the noise floor and are not claims.")
w()

w("## What this supports")
w()
w(
    "The instability documented in `07_stability.md` sits upstream of everything here. "
    "Two risk models built on different halves of the same cohort already disagree "
    "substantially about who belongs at the top of the list. Any argument about whether "
    "a different ranking would be better has to clear that bar first, and much of the "
    "parameter space does not."
)
w()
w(
    "Where the divergence does clear it, the condition is specific: strongly saturating "
    "efficacy and capacity large enough that the ranking is not dominated by a handful "
    "of near tied students. Whether a real intervention saturates that strongly is an "
    "empirical question about a particular programme, which this analysis cannot answer "
    "and which almost no institution has measured."
)
w()

stats["gammas"] = GAMMAS
stats["capacity_pct"] = CAPACITY_PCT
stats["ate_target"] = ATE_TARGET
stats["min_cohort"] = MIN_COHORT
stats["n_replications"] = N_REPLICATIONS
stats["seed"] = SEED
stats["cohorts"] = {str(k): v for k, v in cohort_list.items()}
stats["noise_floor"] = {str(D): {f"{p:.2f}": float(v) for p, v in f.items()} for D, f in floors.items()}

(DOCS / "06_allocation.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "allocation_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print(f"Wrote data/processed/allocation_curves.parquet  ({len(cur):,} rows)")
print("Wrote docs/06_allocation.md")
print("Wrote cache/allocation_stats.json")
