"""
07_stability.py

Asks whether the noise floor in 06_allocation.md is a property of the problem or a
property of my estimator choice.

06 found that two risk models fit on bootstrap resamples of the same cohort agree on
only 8% of their top 1% at day 0, and 26% of their top 5%. That floor was high enough to
absorb most of the risk versus effect divergence. Before reporting that as a finding, it
has to be established which of two things is true:

  Reading A. Risk rankings are intrinsically unstable at the top. Predicted risk is
             nearly flat across the highest scoring students, so small perturbations
             reshuffle the priority list. If so, the instability is a real property of
             risk based allocation and is itself the more important result: an
             institution's call list is not reproducible, and neither ranking can be
             defended.

  Reading B. The floor is an artifact of using a single HistGradientBoosting fit, which
             is a high variance estimator. A bagged or lower variance model would produce
             stable rankings, the floor would drop, and the divergence measured in 06
             would become interpretable again.

Three estimators are compared on the same cohorts:

    single      one HistGradientBoosting fit, as used in 04 and 06
    bagged      mean predicted probability over BAG_SIZE fits on bootstrap resamples
    logistic    L2 logistic regression, higher bias and much lower variance

For each, two independent replications are trained on disjoint bootstrap resamples and
their top k sets compared. Discrimination is reported alongside, because a perfectly
stable model that ranks badly has bought nothing.

A separate diagnostic reports the spread of predicted risk inside the top decile. If the
scores there are nearly tied, instability follows arithmetically and no estimator choice
will fix it.

Usage:
    python 07_stability.py

Reads:
    data/processed/features_d{D}.parquet

Writes:
    docs/07_stability.md
    cache/stability_stats.json
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

DAYS = [0, 28]
CAPACITY_PCT = [0.01, 0.02, 0.05, 0.10, 0.20]
N_REPLICATIONS = 10
BAG_SIZE = 25
MIN_COHORT = 1500
SEED = 20260821

CATEGORICAL = [
    "gender",
    "region",
    "highest_education",
    "imd_band",
    "age_band",
    "disability",
]
DROP = ["id_student", "fold", "outcome", "code_module", "code_presentation"]

rng = np.random.default_rng(SEED)
stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


def topk(x, k):
    idx = np.argsort(-x, kind="stable")[:k]
    m = np.zeros(len(x), dtype=bool)
    m[idx] = True
    return m


def build_hgb(X, cats):
    Xe = X.copy()
    for c in cats:
        Xe[c] = Xe[c].astype("object").where(Xe[c].notna(), "__missing__")
    if cats:
        Xe[cats] = OrdinalEncoder(
            handle_unknown="use_encoded_value", unknown_value=-1
        ).fit_transform(Xe[cats])
    Xe = Xe.astype(float)
    return Xe, [c in cats for c in Xe.columns]


def fit_single(Xe, y, idx, mask, seed):
    clf = HistGradientBoostingClassifier(
        categorical_features=mask,
        random_state=seed,
        early_stopping=True,
        validation_fraction=0.15,
    )
    clf.fit(Xe.iloc[idx], y[idx])
    return clf.predict_proba(Xe)[:, 1]


def fit_bagged(Xe, y, idx, mask, seed, bag):
    sub = rng.integers(0, len(idx), (bag, len(idx)))
    preds = np.zeros(len(Xe))
    for b in range(bag):
        take = idx[sub[b]]
        clf = HistGradientBoostingClassifier(
            categorical_features=mask,
            random_state=seed + b,
            early_stopping=True,
            validation_fraction=0.15,
        )
        clf.fit(Xe.iloc[take], y[take])
        preds += clf.predict_proba(Xe)[:, 1]
    return preds / bag


def fit_logistic(X, y, idx, cats, nums):
    pre = ColumnTransformer(
        [
            ("cat", OneHotEncoder(handle_unknown="ignore", min_frequency=20), cats),
            ("num", make_pipeline(SimpleImputer(strategy="median"), StandardScaler()), nums),
        ]
    )
    pipe = make_pipeline(pre, LogisticRegression(max_iter=2000, C=1.0))
    pipe.fit(X.iloc[idx], y[idx])
    return pipe.predict_proba(X)[:, 1]


w("# 07. Ranking stability")
w()
w("Generated by `07_stability.py`. Do not edit by hand.")
w()
w(
    "`06_allocation.md` found that two risk models fit on resamples of the same cohort "
    "agree on only 8% of their top 1%. That floor absorbed most of the measured "
    "divergence between risk ranking and effect ranking. This document establishes "
    "whether the floor is a property of risk based allocation or a property of the "
    "estimator used to produce it."
)
w()
w(
    f"Three estimators, {N_REPLICATIONS} replications each. Two independent bootstrap "
    "resamples per replication, top k sets compared."
)
w()

results = {}

for D in DAYS:
    feat = pd.read_parquet(PROC / f"features_d{D}.parquet")
    sizes = feat.groupby(["code_module", "code_presentation"]).size()
    mp = sizes[sizes >= MIN_COHORT].idxmax()
    sub = feat[
        (feat["code_module"] == mp[0]) & (feat["code_presentation"] == mp[1])
    ].reset_index(drop=True)

    cols = [c for c in sub.columns if c not in DROP]
    cats = [c for c in CATEGORICAL if c in cols]
    nums = [c for c in cols if c not in cats]
    X = sub[cols]
    y = sub["outcome"].to_numpy()
    n = len(sub)

    Xe, mask = build_hgb(X, cats)

    per = {m: {f"{p:.2f}": [] for p in CAPACITY_PCT} for m in ("single", "bagged", "logistic")}
    aucs = {m: [] for m in ("single", "bagged", "logistic")}

    for rep in range(N_REPLICATIONS):
        i1 = rng.integers(0, n, n)
        i2 = rng.integers(0, n, n)
        s = int(rng.integers(1e6))

        preds = {
            "single": (fit_single(Xe, y, i1, mask, s), fit_single(Xe, y, i2, mask, s + 1)),
            "bagged": (
                fit_bagged(Xe, y, i1, mask, s, BAG_SIZE),
                fit_bagged(Xe, y, i2, mask, s + 100, BAG_SIZE),
            ),
            "logistic": (
                fit_logistic(X, y, i1, cats, nums),
                fit_logistic(X, y, i2, cats, nums),
            ),
        }

        for m, (pa, pb) in preds.items():
            aucs[m].append(roc_auc_score(y, (pa + pb) / 2))
            for p in CAPACITY_PCT:
                k = max(1, int(round(p * n)))
                per[m][f"{p:.2f}"].append((topk(pa, k) & topk(pb, k)).sum() / k)

    # Score spread inside the top decile, from a bagged fit on the full cohort.
    full = fit_bagged(Xe, y, np.arange(n), mask, SEED, BAG_SIZE)
    top = np.sort(full)[::-1][: max(1, int(0.10 * n))]
    spread = {
        "top_decile_min": float(top.min()),
        "top_decile_max": float(top.max()),
        "top_decile_iqr": float(np.percentile(top, 75) - np.percentile(top, 25)),
        "top_decile_median": float(np.median(top)),
    }

    results[str(D)] = {
        "cohort": f"{mp[0]} {mp[1]}",
        "n": int(n),
        "overlap": {
            m: {c: {"mean": float(np.mean(v)), "sd": float(np.std(v, ddof=1))} for c, v in d.items()}
            for m, d in per.items()
        },
        "auc": {m: {"mean": float(np.mean(v)), "sd": float(np.std(v, ddof=1))} for m, v in aucs.items()},
        "score_spread": spread,
    }

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

for D in DAYS:
    r = results[str(D)]
    w(f"## Day {D}, cohort {r['cohort']}, N = {r['n']:,}")
    w()
    w("### Agreement between two independent fits")
    w()
    w("| Estimator | " + " | ".join(f"{p:.0%}" for p in CAPACITY_PCT) + " | AUC |")
    w("|---|" + "---:|" * (len(CAPACITY_PCT) + 1))
    for m in ("single", "bagged", "logistic"):
        cells = " | ".join(
            f"{r['overlap'][m][f'{p:.2f}']['mean']:.2f}" for p in CAPACITY_PCT
        )
        w(f"| {m} | {cells} | {r['auc'][m]['mean']:.3f} |")
    w()

    s = r["score_spread"]
    w("### Score spread in the top decile")
    w()
    w(f"- Median predicted risk: {s['top_decile_median']:.4f}")
    w(f"- Range: {s['top_decile_min']:.4f} to {s['top_decile_max']:.4f}")
    w(f"- Interquartile range: {s['top_decile_iqr']:.4f}")
    w()
    w(
        "If the interquartile range here is small relative to the resampling variation "
        "in individual predictions, the students at the top are close to tied and no "
        "estimator can order them reliably."
    )
    w()

w("## Which reading holds")
w()
w(
    "If bagging raises agreement substantially without costing AUC, the floor in 06 was "
    "an artifact of estimator variance. The allocation analysis should then be rerun on "
    "bagged predictions and the divergence reassessed against the lower floor."
)
w()
w(
    "If bagging changes little, and the logistic model is no better despite far lower "
    "variance, then instability is intrinsic. In that case the more important finding is "
    "not that effect ranking beats risk ranking. It is that a risk ranked priority list "
    "is not reproducible at the capacities institutions actually operate at, which "
    "undermines the practice regardless of which ranking is theoretically correct."
)
w()

stats["results"] = results
stats["n_replications"] = N_REPLICATIONS
stats["bag_size"] = BAG_SIZE
stats["seed"] = SEED

(DOCS / "07_stability.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "stability_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print("Wrote docs/07_stability.md")
print("Wrote cache/stability_stats.json")
