"""
09_findings.py

Assembles the findings document for the education domain.

Nothing here computes anything new. Every figure is read from the cache files written by
scripts 01 through 07, so that no number in the findings document can drift from the
script that produced it. If a figure is not in a cache file, it does not appear.

Limitations are stated before claims, per the project standard.

Usage:
    python 09_findings.py

Reads:
    cache/profile_stats.json
    cache/cohort_stats.json
    cache/feature_stats.json
    cache/risk_stats.json
    cache/cohort_validation_stats.json
    cache/stability_stats.json
    cache/allocation_stats.json
    data/processed/allocation_curves.parquet

Writes:
    docs/09_findings.md
"""

import json
from pathlib import Path

import pandas as pd

CACHE = Path("cache")
PROC = Path("data/processed")
DOCS = Path("docs")


def load(name):
    return json.loads((CACHE / name).read_text(encoding="utf-8"))


profile = load("profile_stats.json")
cohort = load("cohort_stats.json")
feats = load("feature_stats.json")
risk = load("risk_stats.json")["results"]
val = load("cohort_validation_stats.json")["results"]
stab = load("stability_stats.json")["results"]
alloc = load("allocation_stats.json")
curves = pd.read_parquet(PROC / "allocation_curves.parquet")

lines = []


def w(s=""):
    lines.append(s)


w("# 09. Findings, education domain")
w()
w("Generated by `09_findings.py` from the cache files written by scripts 01 to 07.")
w("No figure in this document is typed by hand.")
w()

# ---------------------------------------------------------------------------
# Limitations first
# ---------------------------------------------------------------------------

w("## What this cannot claim")
w()
w(
    "**No treatment effect is estimated.** No randomised experiment is available for this "
    "population. Efficacy is assumed and swept over a one parameter family. Every "
    "statement about effect ranking is conditional on that assumption and on nothing "
    "having been measured about how a real intervention performs."
)
w()
w(
    "**The population is distance learning.** The Open University is not a residential "
    "campus and its attrition dynamics differ. Nothing here transfers to a residential "
    "institution without evidence that has not been gathered."
)
w()

loco0 = val["0"]
w(
    f"**The risk model does not transfer across cohorts.** Held out module AUC ranges "
    f"from {loco0['loco_auc_min']:.3f} to {loco0['loco_auc_max']:.3f} at day 0, and at "
    "least one module sits at chance at three of the four decision points. All "
    "allocation analysis is therefore run within cohort, and no figure here describes "
    "what a model trained on one institution would do at another."
)
w()

cb = profile["check_b"]
w(
    f"**Half of all withdrawals precede the first behavioural decision point.** "
    f"{cb['week_4']['already_gone']:,} registrations have unregistered before day 28. "
    f"After excluding {cohort['exclusions']['unregistered_before_day_0']:,} who never "
    "started, the remainder are real early withdrawals that only a day 0 decision point "
    "can reach."
)
w()

w(
    "**Efficacy is a function of baseline risk alone.** Real heterogeneity depends on "
    "covariates beyond risk. This bounds the divergence attributable to efficacy shape "
    "and understates what a full effect model would find."
)
w()

# ---------------------------------------------------------------------------
# Population
# ---------------------------------------------------------------------------

w("## Population")
w()
w(f"- Registrations after exclusions: **{cohort['n_analysis']:,}**")
w(f"- Excluded: {cohort['n_start'] - cohort['n_analysis']:,} of {cohort['n_start']:,}")
w(f"- Withdrawal rate: **{cohort['outcome']['withdrawal_rate_pct']:.2f}%**")
w(
    f"- Raw rate before excluding pre start unregistrations: "
    f"{profile['outcomes']['withdrawal_rate_pct']:.2f}%"
)
w()
rates = [v["rate_pct"] for v in profile["withdrawal_by_module_presentation"].values()]
w(
    f"Withdrawal varies from {min(rates):.2f}% to {max(rates):.2f}% across the "
    f"{len(rates)} module presentations. Pooled figures obscure this."
)
w()

# ---------------------------------------------------------------------------
# Finding 1
# ---------------------------------------------------------------------------

w("## Finding 1. A risk ranked priority list is not reproducible")
w()
s0 = stab["0"]
ceil1 = s0["overlap"]["ceiling"]["0.01"]["mean"]
log1 = s0["overlap"]["logistic"]["0.01"]["mean"]
single1 = s0["overlap"]["single"]["0.01"]["mean"]
bag1 = s0["overlap"]["bagged"]["0.01"]["mean"]

w(
    f"Two risk models trained on different halves of the same cohort, ranking students "
    f"neither has seen, agree on {log1:.0%} of their top 1% at day 0 using the most "
    f"stable estimator tested. A single gradient boosting fit agrees {single1:.0%} of the "
    f"time; bagging 15 fits raises that only to {bag1:.0%}."
)
w()
w(
    f"The ceiling matters more than any of those. Two models trained on **identical "
    f"data**, differing only in random seed, agree on {ceil1:.0%} of their top 1%. That is "
    "algorithmic nondeterminism alone, and no estimator can beat it."
)
w()
w(
    f"Predicted risk in the top decile has a median of {s0['top_decile_median']:.3f} and "
    f"an interquartile range of {s0['top_decile_iqr']:.3f}. The students at the top are "
    "close to tied. Their true risks differ by less than the error in estimating them, "
    "so ordering them is arbitrary in a way no method resolves."
)
w()
w(
    "**Consequence.** Rerunning the model produces a materially different call list for "
    "the same students. This holds regardless of which ranking rule is theoretically "
    "correct, and it is prior to the question this project set out to ask."
)
w()

# ---------------------------------------------------------------------------
# Finding 2
# ---------------------------------------------------------------------------

w("## Finding 2. Twelve weeks of behavioural data does not improve the ranking")
w()
w("| Decision point | Pooled AUC | Held out module AUC | Withdrawals still reachable |")
w("|---|---:|---:|---:|")
for d in ["0", "28", "56", "84"]:
    reach = cohort["reachability"][d]["addressable_share_pct"]
    w(
        f"| Day {d} | {risk[d]['model']['auc']:.3f} | {val[d]['loco_auc_mean']:.3f} | "
        f"{reach:.1f}% |"
    )
w()
d0, d84 = val["0"]["loco_auc_mean"], val["84"]["loco_auc_mean"]
w(
    f"Under honest transfer conditions the difference between day 0 and day 84 is "
    f"{abs(d84 - d0):.3f} AUC. Fold standard deviation in the risk model was "
    f"{risk['0']['model']['auc_fold_sd']:.3f} to {risk['84']['model']['auc_fold_sd']:.3f}, "
    "so that difference is inside the noise."
)
w()
b1, b2 = risk["84"]["b1_prevalence"]["brier"], risk["84"]["b2_single_feature"]["brier"]
w(
    f"A single clickstream feature barely improves on predicting the base rate: Brier "
    f"{b2:.4f} against {b1:.4f} at day 84. The model's advantage comes from registration "
    "time information, not from watching students click."
)
w()
w(
    f"**Consequence.** The decision point with full reach of every withdrawal carries "
    "no accuracy penalty. Weekly updating risk systems buy precision that the allocation "
    "decision does not use, at the cost of reach it cannot recover."
)
w()

# ---------------------------------------------------------------------------
# Finding 3
# ---------------------------------------------------------------------------

w("## Finding 3. Where effect ranking diverges from risk ranking")
w()
nf = alloc["noise_floor"]["0"]
w(
    "Divergence counts only where the two rankings disagree by more than two independent "
    "risk models disagree with each other. At day 0 that floor is "
    + ", ".join(f"{float(k):.0%}: {v:.2f}" for k, v in nf.items())
    + "."
)
w()

d0c = curves[curves["day"] == 0]
caps = sorted(d0c["capacity_pct"].unique())
gammas = sorted(d0c["gamma"].unique())

w("Day 0, percentage of achievable outcomes averted that risk ranking forgoes.")
w("Cells that did not clear the noise floor are omitted.")
w()
w("| gamma | peak risk | " + " | ".join(f"{c:.0%}" for c in caps) + " |")
w("|---:|---:|" + "---:|" * len(caps))
for g in gammas:
    cells = []
    for c in caps:
        s = d0c[(d0c["gamma"] == g) & (d0c["capacity_pct"] == c)]
        floor = s["noise_floor"].mean()
        if s["overlap"].mean() < floor:
            cells.append(f"{s['value_gap_pct'].mean():.1f}%")
        else:
            cells.append("")
    w(f"| {g:.1f} | {1 / (1 + g):.2f} | " + " | ".join(cells) + " |")
w()

zero = d0c[(d0c["gamma"] >= 1.5) & (d0c["capacity_pct"] == 0.01)]["overlap"].mean()
w(
    f"At gamma of 1.5 or above and 1% capacity, mean overlap between the two rankings is "
    f"{zero:.2f}. The lists are disjoint."
)
w()
w(
    "**Condition.** The result holds from gamma of 1.0 upward, meaning peak intervention "
    "effect at or below 50% baseline risk. Whether a particular programme saturates that "
    "strongly is an empirical question about that programme. Almost no institution has "
    "measured it, which is the practical finding underneath the statistical one."
)
w()

# ---------------------------------------------------------------------------
# Corrections
# ---------------------------------------------------------------------------

w("## Corrections made during the analysis")
w()
w(
    "Two errors were found and fixed after producing results. Both are recorded because "
    "an analysis that reports only its final state is not checkable."
)
w()
w(
    "**Degenerate baseline.** The single feature baseline in `04_risk_model.py` used a "
    "variable carrying a sentinel of 999 for students never active. After "
    "standardisation this compressed all other students into a sliver near zero and the "
    "baseline silently collapsed to the base rate, making the model appear to beat it "
    "when the comparison was empty."
)
w()
w(
    "**In sample noise floor.** The first versions of `06` and `07` fit models on "
    "bootstrap resamples and predicted on rows those models had trained on. AUC inflated "
    "to 0.93 against an honest 0.70. The noise floor this produced absorbed most of the "
    "measured divergence, and the conclusion drawn from it was wrong in the conservative "
    "direction. Correcting it made the divergence larger, not smaller."
)
w()

# ---------------------------------------------------------------------------
# Open
# ---------------------------------------------------------------------------

w("## Open")
w()
w(
    "- No participant level randomised education experiment has been obtained. Until one "
    "is, this domain sits at tier two of the evidence ladder and the project has no tier "
    "one rung."
)
w(
    "- Leave one cohort out was run on modules only, not on presentations within modules."
)
w(
    "- No analysis of who is reallocated away from under effect ranking. Moving attention "
    "off the highest risk students has distributional consequences that deserve their own "
    "treatment."
)
w("- Sources and licence terms are not yet recorded in `docs/08_sources.md`.")
w()

(DOCS / "09_findings.md").write_text("\n".join(lines), encoding="utf-8")
print("Wrote docs/09_findings.md")
print()
print("\n".join(lines))
