"""
10_distribution.py

Who loses attention when allocation switches from risk ranking to effect ranking.

Effect ranking under a saturating efficacy assumption deliberately moves attention away
from the highest risk people, on the grounds that an intervention will not change their
outcome. That is the entire argument. It is also, stated plainly, a decision to stop
contacting the students most likely to leave.

A project that recommends this without measuring who is dropped has not finished its
work. This script measures it.

Three questions:

  Q1. How much higher is the baseline risk of the people dropped than of the people
      added? This quantifies the trade in its own terms.

  Q2. Among people who actually withdrew, what share does each ranking reach? Effect
      ranking maximises expected outcomes averted under an assumed efficacy model. It
      does not maximise coverage of people who go on to fail, and the gap between those
      two things should be visible rather than implied.

  Q3. Does the switch change the composition of the selected group on attributes where
      that would matter? Deprivation band, declared disability, age band, prior
      education. Reported as representation relative to the cohort, not as a fairness
      verdict, because whether a shift is acceptable is a policy question this analysis
      cannot settle.

DETERMINISM
===========
Predictions are out of fold logistic regression on the folds fixed in `02_cohort.py`.
There is no resampling and no random seed anywhere in this script, so every figure
reproduces exactly on rerun. Scripts 06 and 07 draw from a shared generator and their
figures move slightly between runs; that is a separate fix.

Usage:
    python 10_distribution.py

Reads:
    data/processed/features_d{D}.parquet

Writes:
    docs/10_distribution.md
    cache/distribution_stats.json
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

DAYS = [0, 28]
GAMMAS = [1.0, 2.0, 3.0]
CAPACITY_PCT = [0.05, 0.10]
ATE_TARGET = 0.05
MIN_COHORT = 1500

CATEGORICAL = ["gender", "region", "highest_education", "imd_band", "age_band", "disability"]
DROP = ["id_student", "fold", "outcome", "code_module", "code_presentation"]

# Attributes examined for compositional shift. Deprivation and disability first because
# those are where a shift would matter most.
COMPOSITION = ["imd_band", "disability", "age_band", "highest_education"]

stats = {}
lines = []


def w(s=""):
    lines.append(s)


def topk(x, k):
    idx = np.argsort(-x, kind="stable")[:k]
    m = np.zeros(len(x), dtype=bool)
    m[idx] = True
    return m


def tau_of_r(r, gamma, ate):
    shape = r * (1.0 - r) ** gamma
    m = shape.mean()
    return shape * (ate / m) if m > 0 else np.zeros_like(shape)


def oof_logistic(X, y, folds, cats, nums):
    out = np.zeros(len(X))
    for f in np.unique(folds):
        tr, te = folds != f, folds == f
        pre = ColumnTransformer(
            [
                ("cat", OneHotEncoder(handle_unknown="ignore", min_frequency=20), cats),
                ("num", make_pipeline(SimpleImputer(strategy="median"), StandardScaler()), nums),
            ]
        )
        pipe = make_pipeline(pre, LogisticRegression(max_iter=2000))
        pipe.fit(X[tr], y[tr])
        out[te] = pipe.predict_proba(X[te])[:, 1]
    return out


w("# 10. Distribution")
w()
w("Generated by `10_distribution.py`. Do not edit by hand.")
w()
w(
    "Effect ranking under a saturating efficacy assumption moves attention away from the "
    "highest risk people by design. This document measures who is dropped, what is given "
    "up in coverage of people who actually withdraw, and whether the composition of the "
    "selected group shifts."
)
w()
w(
    "Nothing here is a fairness verdict. Whether a shift is acceptable is a policy "
    "question that depends on what an institution owes to whom, and this analysis cannot "
    "settle it. It can make the shift visible, which is the minimum owed to anyone asked "
    "to adopt the recommendation."
)
w()
w("All predictions are out of fold on the folds fixed in `02_cohort.py`. No randomness.")
w()

rows = []
comp_rows = []

for D in DAYS:
    feat = pd.read_parquet(PROC / f"features_d{D}.parquet")
    sizes = feat.groupby(["code_module", "code_presentation"]).size()
    keep = sizes[sizes >= MIN_COHORT].index

    cols = [c for c in feat.columns if c not in DROP]
    cats = [c for c in CATEGORICAL if c in cols]
    nums = [c for c in cols if c not in cats]

    for mp in keep:
        sub = feat[
            (feat["code_module"] == mp[0]) & (feat["code_presentation"] == mp[1])
        ].reset_index(drop=True)
        y = sub["outcome"].to_numpy()
        r = oof_logistic(sub[cols], y, sub["fold"].to_numpy(), cats, nums)
        n = len(sub)

        for g in GAMMAS:
            tau = tau_of_r(r, g, ATE_TARGET)
            for p in CAPACITY_PCT:
                k = max(1, int(round(p * n)))
                mr, me = topk(r, k), topk(tau, k)
                dropped = mr & ~me
                added = me & ~mr

                rows.append(
                    {
                        "day": D,
                        "cohort": f"{mp[0]} {mp[1]}",
                        "n": n,
                        "gamma": g,
                        "capacity_pct": p,
                        "k": k,
                        "n_dropped": int(dropped.sum()),
                        "risk_dropped": float(r[dropped].mean()) if dropped.any() else np.nan,
                        "risk_added": float(r[added].mean()) if added.any() else np.nan,
                        "risk_risklist": float(r[mr].mean()),
                        "risk_effectlist": float(r[me].mean()),
                        "withdrew_covered_risk": int(y[mr].sum()),
                        "withdrew_covered_effect": int(y[me].sum()),
                        "withdrew_total": int(y.sum()),
                        "withdrew_rate_dropped": float(y[dropped].mean()) if dropped.any() else np.nan,
                        "withdrew_rate_added": float(y[added].mean()) if added.any() else np.nan,
                    }
                )

                for attr in COMPOSITION:
                    if attr not in sub.columns:
                        continue
                    vals = sub[attr].astype("object").where(sub[attr].notna(), "__missing__")
                    for level in vals.unique():
                        lm = (vals == level).to_numpy()
                        comp_rows.append(
                            {
                                "day": D,
                                "cohort": f"{mp[0]} {mp[1]}",
                                "gamma": g,
                                "capacity_pct": p,
                                "attribute": attr,
                                "level": str(level),
                                "share_cohort": float(lm.mean()),
                                "share_risklist": float(lm[mr].mean()),
                                "share_effectlist": float(lm[me].mean()),
                            }
                        )

df = pd.DataFrame(rows)
comp = pd.DataFrame(comp_rows)

# ---------------------------------------------------------------------------
# Q1. The trade in its own terms
# ---------------------------------------------------------------------------

w("## Q1. How much higher is the risk of those dropped")
w()
w(
    "At each capacity, switching from risk ranking to effect ranking drops some people "
    "and adds others. Mean predicted risk of each group, averaged across cohorts."
)
w()
for D in DAYS:
    w(f"**Day {D}**")
    w()
    w("| gamma | capacity | Dropped | Mean risk dropped | Mean risk added | Difference |")
    w("|---:|---:|---:|---:|---:|---:|")
    for g in GAMMAS:
        for p in CAPACITY_PCT:
            s = df[(df["day"] == D) & (df["gamma"] == g) & (df["capacity_pct"] == p)]
            rd, ra = s["risk_dropped"].mean(), s["risk_added"].mean()
            share = s["n_dropped"].sum() / s["k"].sum() * 100
            w(
                f"| {g:.1f} | {p:.0%} | {share:.0f}% of list | {rd:.3f} | {ra:.3f} | "
                f"{rd - ra:+.3f} |"
            )
    w()

# ---------------------------------------------------------------------------
# Q2. Coverage of actual withdrawals
# ---------------------------------------------------------------------------

w("## Q2. Coverage of people who actually withdrew")
w()
w(
    "Effect ranking maximises expected outcomes averted under an assumed efficacy model. "
    "It does not maximise the number of eventual withdrawals contacted. This is the gap "
    "between those two objectives."
)
w()
for D in DAYS:
    w(f"**Day {D}**")
    w()
    w("| gamma | capacity | Withdrawals reached by risk | by effect | Change |")
    w("|---:|---:|---:|---:|---:|")
    for g in GAMMAS:
        for p in CAPACITY_PCT:
            s = df[(df["day"] == D) & (df["gamma"] == g) & (df["capacity_pct"] == p)]
            cr = s["withdrew_covered_risk"].sum() / s["withdrew_total"].sum() * 100
            ce = s["withdrew_covered_effect"].sum() / s["withdrew_total"].sum() * 100
            w(f"| {g:.1f} | {p:.0%} | {cr:.1f}% | {ce:.1f}% | {ce - cr:+.1f} pts |")
    w()
w(
    "A negative change means effect ranking contacts fewer of the students who go on to "
    "withdraw. Under the efficacy assumption it still averts more outcomes, because the "
    "people it drops were assumed unreachable. If that assumption is wrong, this column "
    "is the size of the mistake."
)
w()

# ---------------------------------------------------------------------------
# Q3. Composition
# ---------------------------------------------------------------------------

w("## Q3. Composition of the selected group")
w()
w(
    "Share of the selected list belonging to each level, against the share in the cohort. "
    "Shown at gamma 2.0 and 10% capacity, one representative setting. Full results are in "
    "`cache/distribution_stats.json`."
)
w()

sel = comp[(comp["gamma"] == 2.0) & (comp["capacity_pct"] == 0.10)]
for D in DAYS:
    w(f"**Day {D}**")
    w()
    w("| Attribute | Level | Cohort | Risk list | Effect list | Effect minus cohort |")
    w("|---|---|---:|---:|---:|---:|")
    sd = sel[sel["day"] == D]
    for attr in COMPOSITION:
        a = sd[sd["attribute"] == attr]
        for level in sorted(a["level"].unique()):
            l = a[a["level"] == level]
            c, rl, el = (
                l["share_cohort"].mean(),
                l["share_risklist"].mean(),
                l["share_effectlist"].mean(),
            )
            w(
                f"| {attr} | {level} | {c:.3f} | {rl:.3f} | {el:.3f} | {el - c:+.3f} |"
            )
    w()

w("## How to read this")
w()
w(
    "The dropped group is by construction the highest risk part of the list. Q1 gives the "
    "size of that gap and Q2 gives what it costs in coverage of eventual withdrawals. "
    "Neither is an argument against effect ranking. Both are facts that have to accompany "
    "the recommendation, because an institution adopting it is choosing to contact fewer "
    "of the students most likely to leave, and should do so knowingly."
)
w()
w(
    "Compositional shifts in Q3 are descriptive. A shift away from the most deprived band "
    "would be a serious matter; a shift towards it would not automatically be a good one. "
    "Either way the number belongs in front of whoever makes the decision."
)
w()

stats["summary"] = df.to_dict(orient="records")
stats["composition"] = comp.to_dict(orient="records")
stats["gammas"] = GAMMAS
stats["capacity_pct"] = CAPACITY_PCT
stats["ate_target"] = ATE_TARGET

(DOCS / "10_distribution.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "distribution_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print("Wrote docs/10_distribution.md")
print("Wrote cache/distribution_stats.json")
print()
print("\n".join(lines))
