"""
11_mimic_profile.py

Profiles MIMIC-IV v3.1 for the academic medical center domain.

Same discipline as `01_data_profile.py`. Every figure that appears in
`docs/11_mimic_profile.md` is produced here. Nothing is quoted from memory or from
convention.

The convention this script is written to interrogate is the thirty day readmission
window. Thirty days is a reimbursement rule, not a clinical fact. If readmission risk
does not have a natural break there, then choosing it is a choice and must be recorded as
one. The script computes the full distribution of time to next admission so the choice
can be made from the data.

Four checks, all of which can change the design:

  Check A. Do admissions overlap within a patient? If a patient has two admissions whose
           intervals overlap, either the data has an error or the second is a transfer
           rather than a readmission, and the outcome definition breaks.

  Check B. How large is each candidate exclusion? Death in hospital, discharge to
           hospice, transfer to another facility, and elective admission are all
           defensible exclusions with defensible arguments against. Their sizes decide
           how much they matter.

  Check C. Where does the readmission curve actually bend? Rates at 7, 14, 30, 60, 90,
           180 and 365 days, plus the raw distribution.

  Check D. Right censoring. A patient's last admission has no observable follow up. Dates
           in MIMIC are shifted per patient, so there is no shared calendar end date to
           censor against. This is a real problem and this script measures its size
           rather than assuming it away.

Cohort note. OULAD had time based cohorts. MIMIC does not: dates are randomly shifted per
subject, so two patients are not temporally comparable and no time based grouping is
possible. Clinical service is the candidate replacement for the transfer test in
`05_cohort_validation.py`, and its distribution is profiled here to see whether the
groups are large enough to hold out.

Usage:
    python 11_mimic_profile.py

Reads:
    data/raw/mimic/admissions.csv.gz
    data/raw/mimic/patients.csv.gz
    data/raw/mimic/services.csv.gz

Writes:
    docs/11_mimic_profile.md
    cache/mimic_profile_stats.json
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

RAW = Path("data/raw/mimic")
DOCS = Path("docs")
CACHE = Path("cache")
for p in (DOCS, CACHE):
    p.mkdir(parents=True, exist_ok=True)

WINDOWS = [7, 14, 30, 60, 90, 180, 365]

stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


w("# 11. MIMIC-IV profile")
w()
w("Generated by `11_mimic_profile.py`. Do not edit by hand.")
w()
w("MIMIC-IV v3.1, `hosp` module. Beth Israel Deaconess Medical Center.")
w()

# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------

adm = pd.read_csv(
    RAW / "admissions.csv.gz",
    parse_dates=["admittime", "dischtime", "deathtime", "edregtime", "edouttime"],
)
pat = pd.read_csv(RAW / "patients.csv.gz")
svc = pd.read_csv(RAW / "services.csv.gz")

w("## Table inventory")
w()
w("| Table | Rows | Columns |")
w("|---|---:|---:|")
for name, df in (("admissions", adm), ("patients", pat), ("services", svc)):
    w(f"| {name} | {len(df):,} | {len(df.columns)} |")
w()

n_adm = len(adm)
n_pat = adm["subject_id"].nunique()
w(f"- Hospitalisations: **{n_adm:,}**")
w(f"- Distinct patients in admissions: **{n_pat:,}**")
w(f"- Mean admissions per patient: {n_adm / n_pat:.2f}")
w()

per_pat = adm.groupby("subject_id").size()
w("| Admissions per patient | Patients | Share |")
w("|---|---:|---:|")
for k in [1, 2, 3, 4, 5]:
    c = int((per_pat == k).sum())
    w(f"| {k} | {c:,} | {c / n_pat * 100:.2f}% |")
c = int((per_pat >= 6).sum())
w(f"| 6 or more | {c:,} | {c / n_pat * 100:.2f}% |")
w()
w(
    f"{int((per_pat == 1).sum()):,} patients have exactly one admission and can never be "
    "observed to be readmitted. They are still valid index admissions, but they carry no "
    "positive outcome by construction. See Check D."
)
w()

stats["inventory"] = {
    "admissions": int(n_adm),
    "patients": int(n_pat),
    "mean_adm_per_patient": float(n_adm / n_pat),
    "single_admission_patients": int((per_pat == 1).sum()),
}

# ---------------------------------------------------------------------------
# Check A. Overlapping admissions
# ---------------------------------------------------------------------------

w("## Check A. Do admissions overlap within a patient?")
w()

a = adm[["subject_id", "hadm_id", "admittime", "dischtime"]].sort_values(
    ["subject_id", "admittime"]
).reset_index(drop=True)
a["next_admit"] = a.groupby("subject_id")["admittime"].shift(-1)
a["next_hadm"] = a.groupby("subject_id")["hadm_id"].shift(-1)

overlap = a["next_admit"].notna() & (a["next_admit"] < a["dischtime"])
n_overlap = int(overlap.sum())

w(f"Admissions whose next admission begins before the current one ends: **{n_overlap:,}** "
  f"({n_overlap / n_adm * 100:.3f}%)")
w()
if n_overlap:
    w(
        "These cannot be treated as readmissions. They are most likely transfers, "
        "corrections, or overlapping billing records. They are excluded from the "
        "readmission calculation and the count is reported."
    )
else:
    w("No overlaps. The sequence of admissions per patient is clean.")
w()

stats["check_a"] = {"overlapping_admissions": n_overlap}

# ---------------------------------------------------------------------------
# Check C. Time to next admission
# ---------------------------------------------------------------------------

w("## Check C. Where does the readmission curve bend?")
w()

a = a[~overlap].copy()
a["gap_days"] = (a["next_admit"] - a["dischtime"]).dt.total_seconds() / 86400
has_next = a["gap_days"].notna()

w(f"Index admissions with an observed subsequent admission: {int(has_next.sum()):,} of "
  f"{len(a):,} ({has_next.mean() * 100:.2f}%)")
w()

g = a.loc[has_next, "gap_days"]
w("| Percentile | Days to next admission |")
w("|---:|---:|")
for q in [10, 25, 50, 75, 90]:
    w(f"| {q} | {np.percentile(g, q):.1f} |")
w()

w("| Window (days) | Readmitted | Rate of all index admissions |")
w("|---:|---:|---:|")
win_stats = {}
for wd in WINDOWS:
    n = int(((a["gap_days"] >= 0) & (a["gap_days"] <= wd)).sum())
    rate = n / len(a) * 100
    win_stats[str(wd)] = {"n": n, "rate_pct": round(rate, 4)}
    w(f"| {wd} | {n:,} | {rate:.2f}% |")
w()

r30 = win_stats["30"]["rate_pct"]
r14 = win_stats["14"]["rate_pct"]
r60 = win_stats["60"]["rate_pct"]
w(
    f"Between 14 and 30 days the rate rises {r30 - r14:.2f} points; between 30 and 60 it "
    f"rises {r60 - r30:.2f}. If those increments are similar, there is no natural break "
    "at 30 days and the window is a convention borrowed from reimbursement policy rather "
    "than a property of the data. That is not a reason to abandon it, but it is a reason "
    "to state it and to run the allocation analysis at more than one window."
)
w()

stats["check_c"] = {
    "with_subsequent_admission": int(has_next.sum()),
    "gap_percentiles": {str(q): float(np.percentile(g, q)) for q in [10, 25, 50, 75, 90]},
    "windows": win_stats,
}

# ---------------------------------------------------------------------------
# Check B. Candidate exclusions
# ---------------------------------------------------------------------------

w("## Check B. How large is each candidate exclusion?")
w()
w(
    "Each of these is defensible to exclude and defensible to keep. The size decides how "
    "much the choice matters. None is applied here; this script only measures."
)
w()

died = adm["hospital_expire_flag"] == 1
dl = adm["discharge_location"].fillna("__missing__")
hospice = dl.str.contains("HOSPICE", case=False, na=False)
transfer = dl.str.contains("TRANSFER|ANOTHER|SNF|REHAB|PSYCH|ACUTE", case=False, na=False)
elective = adm["admission_type"].fillna("").str.contains("ELECTIVE|SURGICAL SAME DAY", case=False)

w("| Candidate exclusion | Admissions | Share |")
w("|---|---:|---:|")
excl = {}
for label, mask in [
    ("Died during index admission", died),
    ("Discharged to hospice", hospice),
    ("Discharged to another facility", transfer),
    ("Elective or same day surgical admission", elective),
]:
    n = int(mask.sum())
    excl[label] = {"n": n, "share_pct": round(n / n_adm * 100, 4)}
    w(f"| {label} | {n:,} | {n / n_adm * 100:.2f}% |")
w()
w(
    "Death during the index admission is the only unambiguous exclusion: a patient who "
    "died cannot be readmitted, so including them adds guaranteed negatives and deflates "
    "the rate. The others are judgement calls that belong in `12_mimic_cohort.py` with "
    "their reasoning stated."
)
w()

stats["check_b"] = excl

w("### Discharge location distribution")
w()
w("| Discharge location | Count | Share |")
w("|---|---:|---:|")
for k, v in dl.value_counts().head(15).items():
    w(f"| {k} | {v:,} | {v / n_adm * 100:.2f}% |")
w()

stats["discharge_locations"] = {str(k): int(v) for k, v in dl.value_counts().items()}

w("### Admission type distribution")
w()
w("| Admission type | Count | Share |")
w("|---|---:|---:|")
at = adm["admission_type"].fillna("__missing__")
for k, v in at.value_counts().items():
    w(f"| {k} | {v:,} | {v / n_adm * 100:.2f}% |")
w()

stats["admission_types"] = {str(k): int(v) for k, v in at.value_counts().items()}

# ---------------------------------------------------------------------------
# Check D. Right censoring
# ---------------------------------------------------------------------------

w("## Check D. Right censoring")
w()
w(
    "A patient's final admission has no observable follow up. In a dataset with a shared "
    "calendar end, those admissions would be censored at that date. MIMIC shifts dates "
    "randomly per patient, so there is no shared end and no way to distinguish a patient "
    "who was never readmitted from one whose observation window closed."
)
w()

last_adm = a.groupby("subject_id")["admittime"].transform("max") == a["admittime"]
n_last = int(last_adm.sum())
w(f"- Final admissions, one per patient: **{n_last:,}** ({n_last / len(a) * 100:.2f}% of index admissions)")
w(f"- Non final admissions, follow up observable: {len(a) - n_last:,}")
w()

died_last = adm.set_index("hadm_id")["hospital_expire_flag"].reindex(
    a.loc[last_adm, "hadm_id"]
).fillna(0).astype(int)
w(
    f"Of those final admissions, {int(died_last.sum()):,} ended in death, which resolves "
    "the censoring for those patients: they were genuinely not readmitted. The remaining "
    f"{n_last - int(died_last.sum()):,} are unresolved."
)
w()
w(
    "**This is the largest open methodological problem in this domain.** Options are to "
    "restrict to non final admissions, which biases toward frequently admitted patients; "
    "to treat final admissions as not readmitted, which understates the rate; or to model "
    "time to event with censoring, which changes the outcome from binary and does not fit "
    "the allocation framework used in the education domain. The choice is made in "
    "`12_mimic_cohort.py` and reported with the size of the group it affects."
)
w()

stats["check_d"] = {
    "final_admissions": n_last,
    "final_admissions_ending_in_death": int(died_last.sum()),
    "unresolved": n_last - int(died_last.sum()),
}

# ---------------------------------------------------------------------------
# Service lines
# ---------------------------------------------------------------------------

w("## Clinical service as a grouping variable")
w()
w(
    "Dates are shifted per patient, so no time based cohort exists. Clinical service is "
    "the candidate replacement for the transfer test in `05_cohort_validation.py`. Groups "
    "must be large enough to hold out."
)
w()

first_svc = svc.sort_values("transfertime").groupby("hadm_id")["curr_service"].first()
adm_svc = adm[["hadm_id"]].merge(
    first_svc.rename("service"), left_on="hadm_id", right_index=True, how="left"
)
sv = adm_svc["service"].fillna("__missing__")

w("| Service | Admissions | Share |")
w("|---|---:|---:|")
for k, v in sv.value_counts().items():
    w(f"| {k} | {v:,} | {v / n_adm * 100:.2f}% |")
w()

big = int((sv.value_counts() >= 5000).sum())
w(
    f"{big} services have at least 5,000 admissions. That is the pool available for leave "
    "one service out validation. Services below that threshold are pooled or dropped, and "
    "the choice is recorded."
)
w()

stats["services"] = {str(k): int(v) for k, v in sv.value_counts().items()}

# ---------------------------------------------------------------------------
# Demographics
# ---------------------------------------------------------------------------

w("## Patient demographics")
w()
w(f"- Rows in patients: {len(pat):,}")
w(f"- Anchor age median: {pat['anchor_age'].median():.0f}")
w(f"- Anchor age range: {pat['anchor_age'].min():.0f} to {pat['anchor_age'].max():.0f}")
w()
w("| Gender | Count | Share |")
w("|---|---:|---:|")
for k, v in pat["gender"].value_counts().items():
    w(f"| {k} | {v:,} | {v / len(pat) * 100:.2f}% |")
w()
w(
    "Anchor age is the patient's age in their anchor year. Ages above 89 are grouped in "
    "MIMIC for deidentification, so the top of the range is not a real age and must not be "
    "treated as continuous at that end."
)
w()

stats["demographics"] = {
    "n_patients_table": int(len(pat)),
    "anchor_age_median": float(pat["anchor_age"].median()),
    "gender": {str(k): int(v) for k, v in pat["gender"].value_counts().items()},
}

# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

(DOCS / "11_mimic_profile.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "mimic_profile_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print("Wrote docs/11_mimic_profile.md")
print("Wrote cache/mimic_profile_stats.json")
