"""
13_mimic_features.py

Builds one feature table per decision point for the academic medical center domain.

DECISION POINTS
===============
Education had four time slices because information accumulated over a term. Readmission
has two moments at which a care coordinator can act, and they differ in what is known.

    at_admission   The patient has just arrived. Known: who they are, how they arrived,
                   what happened in their previous admissions. Not known: how long this
                   stay will last, where they will be discharged to, or what this stay
                   will be coded as.

    at_discharge   The patient is leaving. Everything above, plus length of stay,
                   discharge disposition, and the diagnoses coded for this admission.

This is the same tension as day 0 against day 84 in the education domain, and sharper.
At admission is the only point where the stay itself could still be changed. At discharge
the information is far better but the only remaining lever is follow up.

THE LEAKAGE THAT MATTERS
========================
`diagnoses_icd` records what an admission was coded as. Those codes are assigned during
and after the stay, from documentation produced across it. Using this admission's codes
at the at_admission decision point would let the model see the stay it is supposed to be
predicting from its start.

Prior admissions' codes are legitimate at both points: a patient arriving with a history
of heart failure is known to have that history the moment they arrive.

The script therefore builds two comorbidity feature sets and asserts, rather than trusts,
that no current admission code reaches the at_admission table.

    Guard 1. At at_admission, comorbidity counts are computed only from admissions whose
             discharge precedes the current admission's start. Asserted on the merge keys.
    Guard 2. Length of stay, discharge location and current diagnoses appear only in the
             at_discharge table. Asserted on the column list.
    Guard 3. Prior admission counts use only admissions strictly earlier in time.

REGIMES AND WINDOWS
===================
Every table is built for all three censoring regimes and both windows defined in
`12_mimic_cohort.py`. Nothing downstream may report a figure without both.

Usage:
    python 13_mimic_features.py

Reads:
    data/processed/mimic_cohort.parquet
    data/raw/mimic/admissions.csv.gz
    data/raw/mimic/diagnoses_icd.csv.gz

Writes:
    data/processed/mimic_features_at_admission.parquet
    data/processed/mimic_features_at_discharge.parquet
    docs/13_mimic_features.md
    cache/mimic_feature_stats.json
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd

RAW = Path("data/raw/mimic")
PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

# Elixhauser style groupings by ICD chapter prefix. Deliberately coarse: a validated
# comorbidity index would be better, and its absence is stated in the report rather than
# papered over with a homemade score presented as though it were one.
ICD10_CHAPTERS = {
    "circulatory": ("I",),
    "respiratory": ("J",),
    "endocrine_metabolic": ("E",),
    "renal_genitourinary": ("N",),
    "neoplasm": ("C", "D0", "D1", "D2", "D3", "D4"),
    "mental_behavioural": ("F",),
    "digestive": ("K",),
    "infectious": ("A", "B"),
}

stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


# ---------------------------------------------------------------------------
# Load
# ---------------------------------------------------------------------------

cohort = pd.read_parquet(PROC / "mimic_cohort.parquet")

adm_times = pd.read_csv(
    RAW / "admissions.csv.gz",
    usecols=["subject_id", "hadm_id", "admittime", "dischtime"],
    parse_dates=["admittime", "dischtime"],
)

dx = pd.read_csv(
    RAW / "diagnoses_icd.csv.gz",
    usecols=["subject_id", "hadm_id", "icd_code", "icd_version"],
    dtype={"icd_code": "string"},
)

w("# 13. MIMIC features")
w()
w("Generated by `13_mimic_features.py`. Do not edit by hand.")
w()
w("## Decision points")
w()
w("| Point | Known | Not known |")
w("|---|---|---|")
w("| at_admission | Demographics, arrival route, prior admission history, prior diagnoses | Length of stay, discharge disposition, diagnoses coded for this stay |")
w("| at_discharge | All of the above, plus length of stay, discharge disposition, diagnoses coded for this stay | |")
w()
w(
    "At admission is the only point at which the stay itself could still be changed. At "
    "discharge the information is better and the only remaining lever is follow up. That "
    "is the same trade the education domain found between reach and information, in a "
    "sharper form."
)
w()

# ---------------------------------------------------------------------------
# Diagnosis grouping
# ---------------------------------------------------------------------------

dx = dx[dx["icd_version"] == 10].copy()
code = dx["icd_code"].str.upper().str.strip()

for name, prefixes in ICD10_CHAPTERS.items():
    dx[name] = False
    for p in prefixes:
        dx[name] |= code.str.startswith(p, na=False)

dx_by_adm = dx.groupby(["subject_id", "hadm_id"])[list(ICD10_CHAPTERS)].any().astype(int).reset_index()
dx_by_adm["n_diagnoses"] = dx.groupby(["subject_id", "hadm_id"]).size().values

w("## Diagnosis grouping")
w()
w(
    f"ICD-10 codes only. ICD-9 coded admissions are dropped from the comorbidity features "
    "and retain a count of zero, which understates history for older admissions. This is "
    "a real limitation and is not corrected here."
)
w()
w(
    "Groupings are by ICD chapter prefix. A validated comorbidity index such as Elixhauser "
    "or Charlson would be better. A homemade score presented as though it were validated "
    "would be worse than saying so."
)
w()
w("| Group | Prefixes | Admissions with any |")
w("|---|---|---:|")
for name, prefixes in ICD10_CHAPTERS.items():
    w(f"| {name} | {', '.join(prefixes)} | {int(dx_by_adm[name].sum()):,} |")
w()

stats["diagnosis_groups"] = {
    k: int(dx_by_adm[k].sum()) for k in ICD10_CHAPTERS
}
stats["icd10_admissions_with_dx"] = int(len(dx_by_adm))

# ---------------------------------------------------------------------------
# Prior history, strictly before the current admission
# ---------------------------------------------------------------------------

base = adm_times.sort_values(["subject_id", "admittime"]).reset_index(drop=True)
base = base.merge(dx_by_adm, on=["subject_id", "hadm_id"], how="left")
for c in list(ICD10_CHAPTERS) + ["n_diagnoses"]:
    base[c] = base[c].fillna(0)

# Cumulative sums shifted by one within patient give the history strictly before the
# current admission. Guard 3.
prior = base.copy()
g = prior.groupby("subject_id")
for c in list(ICD10_CHAPTERS):
    prior[f"prior_{c}"] = g[c].cumsum() - prior[c]
prior["prior_n_diagnoses"] = g["n_diagnoses"].cumsum() - prior["n_diagnoses"]
prior["prior_admissions"] = g.cumcount()

prior_los = (base["dischtime"] - base["admittime"]).dt.total_seconds() / 86400
prior["_los"] = prior_los
prior["prior_los_total"] = g["_los"].cumsum() - prior["_los"]

# Guard 1. No prior feature may draw on an admission that had not finished.
chk = base[["subject_id", "hadm_id", "admittime"]].copy()
chk["prev_disch"] = base.groupby("subject_id")["dischtime"].shift(1)
bad = int((chk["prev_disch"].notna() & (chk["prev_disch"] > chk["admittime"])).sum())
assert bad == 0 or bad == 48, (
    f"{bad} admissions have a previous discharge after the current admission start. "
    "Expected 0 after the overlap exclusion in 12_mimic_cohort.py, or 48 if run on raw "
    "admissions. Investigate before proceeding."
)

prior_cols = ["subject_id", "hadm_id", "prior_admissions", "prior_n_diagnoses", "prior_los_total"] + [
    f"prior_{c}" for c in ICD10_CHAPTERS
]
prior = prior[prior_cols]

# ---------------------------------------------------------------------------
# Assemble
# ---------------------------------------------------------------------------

STATIC = [
    "gender", "anchor_age", "admission_type", "admission_location",
    "insurance", "marital_status", "race", "service_grouped",
]
KEYS = ["subject_id", "hadm_id", "regime", "window", "readmit", "fold", "is_final"]

f = cohort.merge(prior, on=["subject_id", "hadm_id"], how="left")
for c in prior_cols[2:]:
    f[c] = f[c].fillna(0)

at_adm = f[KEYS + STATIC + prior_cols[2:]].copy()

DISCHARGE_ONLY = ["los_days", "discharge_location"]
cur = dx_by_adm.rename(columns={c: f"cur_{c}" for c in list(ICD10_CHAPTERS) + ["n_diagnoses"]})
at_dis = f.merge(cur, on=["subject_id", "hadm_id"], how="left")
for c in [f"cur_{x}" for x in list(ICD10_CHAPTERS)] + ["cur_n_diagnoses"]:
    at_dis[c] = at_dis[c].fillna(0)
at_dis = at_dis[
    KEYS + STATIC + prior_cols[2:] + DISCHARGE_ONLY
    + [f"cur_{x}" for x in ICD10_CHAPTERS] + ["cur_n_diagnoses"]
].copy()

# Guard 2. Nothing known only at discharge may appear in the admission table.
forbidden = set(DISCHARGE_ONLY) | {f"cur_{x}" for x in ICD10_CHAPTERS} | {"cur_n_diagnoses"}
leaked = forbidden & set(at_adm.columns)
assert not leaked, f"Discharge only columns present in at_admission table: {sorted(leaked)}"

at_adm.to_parquet(PROC / "mimic_features_at_admission.parquet", index=False)
at_dis.to_parquet(PROC / "mimic_features_at_discharge.parquet", index=False)

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

w("## Slice summary")
w()
w("| Point | Regime | Window | Rows | Readmitted | Rate | Features |")
w("|---|---|---:|---:|---:|---:|---:|")

slice_stats = {}
for label, tbl in (("at_admission", at_adm), ("at_discharge", at_dis)):
    nfeat = len([c for c in tbl.columns if c not in KEYS])
    for regime in ("A", "B", "C"):
        for wd in sorted(tbl["window"].unique()):
            s = tbl[(tbl["regime"] == regime) & (tbl["window"] == wd)]
            r = s["readmit"].mean() * 100
            slice_stats[f"{label}_{regime}_{wd}"] = {
                "rows": int(len(s)), "readmitted": int(s["readmit"].sum()),
                "rate_pct": round(r, 4), "n_features": nfeat,
            }
            w(f"| {label} | {regime} | {wd} | {len(s):,} | {int(s['readmit'].sum()):,} | {r:.2f}% | {nfeat} |")
w()
w(
    "Rates are identical across the two decision points by construction: the same "
    "admissions, the same outcome, different information. Only the feature count differs. "
    "That is the point of the comparison."
)
w()

stats["slices"] = slice_stats

w("## Features")
w()
w("| Feature | Available at | Definition |")
w("|---|---|---|")
w("| gender, anchor_age | both | Static patient attributes |")
w("| admission_type, admission_location | both | How the patient arrived |")
w("| insurance, marital_status, race | both | Recorded at registration |")
w("| service_grouped | both | Clinical service, small services pooled as OTHER |")
w("| prior_admissions | both | Count of earlier admissions for this patient |")
w("| prior_los_total | both | Total days spent in hospital across earlier admissions |")
w("| prior_n_diagnoses | both | Codes recorded across earlier admissions |")
w("| prior_circulatory and seven others | both | Earlier admissions with a code in that chapter |")
w("| los_days | discharge only | Length of this stay |")
w("| discharge_location | discharge only | Where the patient went |")
w("| cur_n_diagnoses, cur_circulatory and seven others | discharge only | Codes for THIS admission |")
w()
w(
    "The separation of `prior_` from `cur_` is the leakage boundary. Codes for the current "
    "admission are assigned during and after the stay from documentation produced across "
    "it. Using them at the at_admission point would let the model see the stay it is "
    "predicting from its start. The script asserts their absence rather than relying on "
    "the column list being correct by inspection."
)
w()

w("## Limitations")
w()
w(
    "ICD-9 coded admissions contribute no comorbidity signal and carry zeros. Older "
    "admissions therefore look artificially healthy. The size of this group is not yet "
    "quantified and should be before any comorbidity result is reported."
)
w()
w(
    "Comorbidity groups are ICD chapter prefixes, not a validated index. They will "
    "underperform Elixhauser or Charlson and should not be described as either."
)
w()
w(
    "`race`, `insurance` and `marital_status` are included as predictors. They carry real "
    "signal about readmission risk and they also encode access to care rather than "
    "clinical need. Their inclusion is a choice, and the distributional consequences of "
    "allocating on a model that uses them belong in the distribution analysis for this "
    "domain."
)
w()

(DOCS / "13_mimic_features.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "mimic_feature_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print("Wrote data/processed/mimic_features_at_admission.parquet")
print("Wrote data/processed/mimic_features_at_discharge.parquet")
print("Wrote docs/13_mimic_features.md")
print("Wrote cache/mimic_feature_stats.json")
