"""
15b_mimic_early_stopping.py

Tests a confound in `15_mimic_stability.py` before its conclusion is written down.

THE PROBLEM
===========
`15` fitted gradient boosting with `early_stopping=True, validation_fraction=0.15` on
bootstrap resamples of the training pool. A bootstrap sample of size n drawn with
replacement contains roughly 63% of the distinct rows, which means about a third of the
sample is duplicates. The internal validation split therefore contains rows that also
appear in the training split, so the chosen stopping iteration is selected against
partly contaminated data and will move from resample to resample for reasons that have
nothing to do with the estimator.

Logistic regression has no early stopping and is not exposed to this. The comparison in
`15` may therefore be unfair in a way that flatters logistic.

`15` found logistic more stable than gradient boosting in 12 of 12 cells at the top
decile, and gradient boosting below the not usable threshold in 12 of 12 cells at one
percent capacity. That is a strong claim and it should not rest on a design flaw.

WHAT THIS DOES
==============
Refits gradient boosting on the identical bootstrap resamples, identical seeds, identical
fixed evaluation fold, with early stopping switched off and a fixed iteration count. The
only thing that changes is the stopping rule. Everything else is byte for byte the
protocol `15` used, so the two arms are directly comparable.

The existing early stopping numbers are read from `cache/mimic_stability_stats.json`
rather than refitted, which halves the runtime and guarantees the comparison arm is the
exact set of numbers already reported.

HOW TO READ THE RESULT
======================
    Fixed iteration Jaccard close to the early stopping Jaccard
        The instability is inherent to the estimator. `15` stands as written.

    Fixed iteration Jaccard materially higher, approaching logistic
        A large part of what `15` measured was the stopping rule, not the estimator.
        The conclusion has to be restated and `15` rerun with this configuration.

    Fixed iteration Jaccard lower
        Early stopping was helping. The gap to logistic is real and larger than reported.

No threshold is pre registered for the size of "materially", because the question here is
not pass or fail. It is how much of a measured effect is attributable to a design choice,
and that is a quantity to report rather than a verdict to reach.

WHAT THIS DOES NOT ADDRESS
==========================
Not whether 100 iterations is the right count. It is fixed rather than tuned, for the
same reason `14` did no hyperparameter search, and a different count would give different
numbers. The claim is comparative, not absolute.

Not the logistic arm, which is unchanged and not refitted.

Usage:
    python 15b_mimic_early_stopping.py

Reads:
    data/processed/mimic_features_at_admission.parquet
    data/processed/mimic_features_at_discharge.parquet
    cache/mimic_stability_stats.json

Writes:
    docs/15b_mimic_early_stopping.md
    cache/mimic_early_stopping_stats.json
"""

import json
import time
import warnings
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.preprocessing import OrdinalEncoder

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

POINTS = ["at_admission", "at_discharge"]
REGIMES = ["A", "B", "C"]
WINDOWS = [30, 90]

R = 10
CAPACITIES = [0.01, 0.05, 0.10, 0.20]
HEADLINE_CAPACITY = 0.10
MAX_ITER = 100

SEED = 20260821

CATEGORICAL = [
    "gender", "admission_type", "admission_location", "insurance",
    "marital_status", "race", "service_grouped", "discharge_location",
]
DROP = ["subject_id", "hadm_id", "regime", "window", "readmit", "fold", "is_final"]

prior = json.loads((CACHE / "mimic_stability_stats.json").read_text(encoding="utf-8"))
assert prior["repeats"] == R, "repeat count must match the run being compared against"
assert prior["seed"] == SEED, "seed must match the run being compared against"

stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


def top_k_set(scores, k):
    return set(np.argsort(-scores, kind="stable")[:k].tolist())


def jaccard(a, b):
    return len(a & b) / len(a | b) if (a | b) else np.nan


w("# 15b. Is gradient boosting instability an early stopping artifact?")
w()
w("Generated by `15b_mimic_early_stopping.py`. Do not edit by hand.")
w()
w(
    "`15` fitted gradient boosting with early stopping on bootstrap resamples. About a "
    "third of a bootstrap sample is duplicated rows, so the internal validation split "
    "shares rows with the training split and the stopping iteration moves for reasons "
    "unrelated to the estimator. Logistic regression is not exposed to this. This script "
    "refits the same resamples with early stopping off and a fixed "
    f"{MAX_ITER} iterations, changing nothing else."
)
w()

results = {}
t0 = time.time()

for point in POINTS:
    tbl = pd.read_parquet(PROC / f"mimic_features_{point}.parquet")
    feat_cols = [c for c in tbl.columns if c not in DROP]
    cats = [c for c in CATEGORICAL if c in feat_cols]

    for regime in REGIMES:
        for wd in WINDOWS:
            s = tbl[(tbl["regime"] == regime) & (tbl["window"] == wd)].reset_index(drop=True)
            y = s["readmit"].to_numpy()
            folds = s["fold"].to_numpy()

            eval_fold = sorted(np.unique(folds))[-1]
            te = folds == eval_fold
            tr_pool = np.flatnonzero(folds != eval_fold)
            n_eval = int(te.sum())

            X = s[feat_cols].copy()
            for c in cats:
                X[c] = X[c].astype("object").where(X[c].notna(), "__missing__")
            Xe = X.copy()
            if cats:
                Xe[cats] = OrdinalEncoder(
                    handle_unknown="use_encoded_value", unknown_value=-1
                ).fit_transform(X[cats])
            Xe = Xe.astype(float)
            mask = [c in cats for c in Xe.columns]
            Xe_te = Xe[te]

            preds = []
            for r in range(R):
                rng = np.random.default_rng(SEED + r)
                boot = rng.choice(tr_pool, size=len(tr_pool), replace=True)
                clf = HistGradientBoostingClassifier(
                    categorical_features=mask, random_state=SEED + r,
                    early_stopping=False, max_iter=MAX_ITER,
                )
                clf.fit(Xe.iloc[boot], y[boot])
                preds.append(clf.predict_proba(Xe_te)[:, 1])

            P = np.vstack(preds)
            key = f"{point}_{regime}_{wd}"
            entry = {
                "point": point, "regime": regime, "window": wd,
                "n_eval": n_eval, "capacities": {},
            }

            rho = [
                float(spearmanr(P[i], P[j]).statistic)
                for i, j in combinations(range(R), 2)
            ]
            entry["spearman_median"] = float(np.median(rho))

            for cap in CAPACITIES:
                k = max(1, int(round(cap * n_eval)))
                sets = [top_k_set(P[i], k) for i in range(R)]
                js = [jaccard(a, b) for a, b in combinations(sets, 2)]
                core = set.intersection(*sets)
                union = set().union(*sets)
                sums = np.array([P[i][sorted(sets[i])].sum() for i in range(R)])
                entry["capacities"][f"{cap:.2f}"] = {
                    "k": k,
                    "jaccard_median": float(np.median(js)),
                    "core_frac_of_k": float(len(core) / k),
                    "union_over_k": float(len(union) / k),
                    "sum_cv": float(sums.std(ddof=1) / sums.mean()),
                }

            results[key] = entry
            print(f"  done {key}  ({time.time() - t0:.0f}s elapsed)")

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

cap_key = f"{HEADLINE_CAPACITY:.2f}"


def prior_j(key, est, cap):
    return prior["results"][key][est]["capacities"][f"{cap:.2f}"]["jaccard_median"]


w("## Top decile, three arms")
w()
w(
    "Early stopping and logistic are the numbers already reported in `15`. Fixed "
    "iteration is new. The gap column is how much of the distance between the two "
    "estimators closes when the stopping rule is removed."
)
w()
w("| Point | Regime | Window | Early stopping | Fixed iteration | Logistic | Gap closed |")
w("|---|---|---:|---:|---:|---:|---:|")
for key, r in results.items():
    es = prior_j(key, "hgb", HEADLINE_CAPACITY)
    fx = r["capacities"][cap_key]["jaccard_median"]
    lg = prior_j(key, "logit", HEADLINE_CAPACITY)
    closed = (fx - es) / (lg - es) if abs(lg - es) > 1e-9 else np.nan
    w(
        f"| {r['point']} | {r['regime']} | {r['window']} | {es:.3f} | {fx:.3f} | "
        f"{lg:.3f} | {closed:+.1%} |"
    )
w()

w("## One percent capacity, three arms")
w()
w(
    "This is where `15` placed gradient boosting below the not usable threshold in every "
    "cell, and it is the capacity the project is most interested in."
)
w()
w("| Point | Regime | Window | Early stopping | Fixed iteration | Logistic |")
w("|---|---|---:|---:|---:|---:|")
for key, r in results.items():
    w(
        f"| {r['point']} | {r['regime']} | {r['window']} | "
        f"{prior_j(key, 'hgb', 0.01):.3f} | "
        f"{r['capacities']['0.01']['jaccard_median']:.3f} | "
        f"{prior_j(key, 'logit', 0.01):.3f} |"
    )
w()

w("## Fixed iteration, full capacity sweep")
w()
w("| Point | Regime | Window | 1% | 5% | 10% | 20% | Core | Union over k | CV |")
w("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|")
for key, r in results.items():
    js = " | ".join(
        f"{r['capacities'][f'{c:.2f}']['jaccard_median']:.3f}" for c in CAPACITIES
    )
    c = r["capacities"][cap_key]
    w(
        f"| {r['point']} | {r['regime']} | {r['window']} | {js} | "
        f"{c['core_frac_of_k']:.3f} | {c['union_over_k']:.3f} | {c['sum_cv']:.4f} |"
    )
w()

es_all = np.array([prior_j(k, "hgb", HEADLINE_CAPACITY) for k in results])
fx_all = np.array([r["capacities"][cap_key]["jaccard_median"] for r in results.values()])
lg_all = np.array([prior_j(k, "logit", HEADLINE_CAPACITY) for k in results])

w("## What this means for `15`")
w()
w("| Arm | Mean top decile Jaccard |")
w("|---|---:|")
w(f"| Gradient boosting, early stopping | {es_all.mean():.3f} |")
w(f"| Gradient boosting, fixed iteration | {fx_all.mean():.3f} |")
w(f"| Logistic | {lg_all.mean():.3f} |")
w()
w(
    f"Removing the stopping rule moves gradient boosting by {fx_all.mean() - es_all.mean():+.3f} "
    f"on average, against a remaining distance to logistic of {lg_all.mean() - fx_all.mean():.3f}. "
    f"Fixed iteration still trails logistic in "
    f"{int((lg_all > fx_all).sum())} of {len(results)} cells."
)
w()
w(
    "If the remaining gap is most of the original, the instability is the estimator and "
    "`15` stands. If the stopping rule accounts for most of it, `15` must be rerun with "
    "early stopping off before its conclusion is used, and the version already committed "
    "should be marked superseded rather than deleted."
)
w()

stats["results"] = results
stats["seed"] = SEED
stats["repeats"] = R
stats["max_iter"] = MAX_ITER
stats["runtime_seconds"] = round(time.time() - t0, 1)

(DOCS / "15b_mimic_early_stopping.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "mimic_early_stopping_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print(f"Total runtime: {time.time() - t0:.0f}s")
print("Wrote docs/15b_mimic_early_stopping.md")
print("Wrote cache/mimic_early_stopping_stats.json")
