"""
16b_mimic_convergence.py

Rules out an alternative explanation for the headline finding in `16`.

THE PROBLEM
===========
`14`, `15` and `16` all begin with:

    warnings.filterwarnings("ignore", category=UserWarning)

`ConvergenceWarning` is a subclass of `UserWarning`, so if lbfgs hit `max_iter=1000`
without converging, nothing was printed and nothing was recorded. Every logistic fit in
the project was made under that filter.

This matters now rather than earlier because of what `16` found. Level transferred in only
26 of 136 service cells, with a worst gap of 0.3187, while ranking transferred in 122.
A non converged logistic fit produces exactly that signature: the coefficient directions
settle early and give a usable ordering, while the intercept and the coefficient
magnitudes are still moving when the optimizer stops, so predicted probabilities are off
in level.

In other words, the alternative explanation predicts the same pattern as the substantive
one, and the two cannot be separated by looking at `16`'s output.

WHAT THIS DOES
==============
Refits selected service cells exactly as `16` did, changing only two things:

    `n_iter_` is read off the fitted model and reported, so convergence is observed
    rather than assumed.

    Each fit is repeated at `max_iter` 1000 and 5000. If the level gap is unchanged when
    the optimizer is given five times the budget, non convergence is not the cause.

The reported level gap is directly comparable to the corresponding row of
`docs/16_mimic_validation.md`, so the two can be read side by side.

WHY THESE CELLS
===============
Regime A only, which keeps every slice at 321,547 rows and avoids the discharge regime B
slices that made `16` an overnight job.

    OBS   the worst transfer penalty in `16` and the service most likely to strain a
          model fitted without it
    MED   51.73% of admissions, the mild case, included as a contrast
    CMED  a mid sized service with a near zero capture delta

If OBS converges and its level gap survives a five fold increase in iteration budget,
the finding in `16` is about the population and not the optimizer.

WHAT THIS DOES NOT ESTABLISH
============================
Not convergence in the cells not tested. Regime B at discharge is the largest and slowest
configuration and is deliberately skipped. If regime A converges comfortably, regime B is
unlikely to differ in kind, but this does not prove it.

Not that the level gap has no other cause. It rules out one explanation.

Usage:
    python 16b_mimic_convergence.py

Writes:
    docs/16b_mimic_convergence.md
    cache/mimic_convergence_stats.json
"""

import json
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.exceptions import ConvergenceWarning
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

PROC = Path("data/processed")
DOCS = Path("docs")
CACHE = Path("cache")

REGIME = "A"
POINTS = ["at_admission", "at_discharge"]
WINDOWS = [30, 90]
SERVICES = ["OBS", "MED", "CMED"]
MAX_ITERS = [1000, 5000]

CAPACITIES = [0.01, 0.05, 0.10, 0.20]
HEADLINE_CAPACITY = 0.10
SEED = 20260821

SERVICE_COL = "service_grouped"
CATEGORICAL = [
    "gender", "admission_type", "admission_location", "insurance",
    "marital_status", "race", "discharge_location",
]
DROP = ["subject_id", "hadm_id", "regime", "window", "readmit", "fold", "is_final", SERVICE_COL]

stats = {}
lines = []


def w(s=""):
    lines.append(s)
    print(s)


def capture(y, p, cap):
    k = max(1, int(round(cap * len(p))))
    sel = np.argsort(-p, kind="stable")[:k]
    return float(y[sel].sum() / y.sum()) if y.sum() else np.nan


def fit_logit(Xtr, ytr, Xte, cats, nums, max_iter):
    pre = ColumnTransformer([
        ("cat", OneHotEncoder(handle_unknown="ignore", min_frequency=50), cats),
        ("num", make_pipeline(SimpleImputer(strategy="median"), StandardScaler()), nums),
    ])
    clf = LogisticRegression(max_iter=max_iter, solver="lbfgs")
    pipe = make_pipeline(pre, clf)

    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always", ConvergenceWarning)
        pipe.fit(Xtr, ytr)
        warned = any(issubclass(x.category, ConvergenceWarning) for x in caught)

    return pipe.predict_proba(Xte)[:, 1], int(clf.n_iter_[0]), warned


w("# 16b. Did the logistic fits actually converge?")
w()
w("Generated by `16b_mimic_convergence.py`. Do not edit by hand.")
w()
w(
    "Every logistic fit in `14`, `15` and `16` ran under a filter that suppresses "
    "`ConvergenceWarning`. A fit that stopped at the iteration cap would produce the same "
    "signature `16` reported: an ordering that transfers alongside a level that does not. "
    "This script observes the iteration count directly and refits at five times the "
    "budget to see whether the level gap moves."
)
w()
w(
    f"Regime {REGIME} only, so every slice is the smaller 321,547 row configuration. "
    "Services chosen as the worst case, the largest case and a middling case from `16`."
)
w()

results = {}
t0 = time.time()

for point in POINTS:
    tbl = pd.read_parquet(PROC / f"mimic_features_{point}.parquet")
    feat_cols = [c for c in tbl.columns if c not in DROP]
    cats = [c for c in CATEGORICAL if c in feat_cols]
    nums = [c for c in feat_cols if c not in cats]

    for wd in WINDOWS:
        s = tbl[(tbl["regime"] == REGIME) & (tbl["window"] == wd)].reset_index(drop=True)
        y = s["readmit"].to_numpy()
        svc_all = s[SERVICE_COL].astype(str).to_numpy()

        X = s[feat_cols].copy()
        for c in cats:
            X[c] = X[c].astype("object").where(X[c].notna(), "__missing__")

        for svc in SERVICES:
            idx_s = np.flatnonzero(svc_all == svc)
            if len(idx_s) == 0:
                print(f"  skip {point}_{wd}_{svc}, service absent")
                continue

            rng = np.random.default_rng(SEED)
            idx_s = idx_s.copy()
            rng.shuffle(idx_s)
            half = len(idx_s) // 2
            half_a, half_b = idx_s[:half], idx_s[half:]
            non_s = np.flatnonzero(svc_all != svc)

            loso_tr = non_s
            keep = rng.choice(non_s, size=len(non_s) - len(half_a), replace=False)
            ctrl_tr = np.concatenate([keep, half_a])
            assert len(loso_tr) == len(ctrl_tr), "training arms must be size matched"

            y_te = y[half_b]
            key = f"{point}_{wd}_{svc}"
            entry = {"point": point, "window": wd, "service": svc,
                     "n_test": int(len(half_b)), "arms": {}}

            for mi in MAX_ITERS:
                for arm, tr in (("loso", loso_tr), ("control", ctrl_tr)):
                    p, n_iter, warned = fit_logit(
                        X.iloc[tr], y[tr], X.iloc[half_b], cats, nums, mi
                    )
                    entry["arms"][f"{arm}_{mi}"] = {
                        "n_iter": n_iter,
                        "hit_cap": bool(n_iter >= mi),
                        "warned": warned,
                        "auc": float(roc_auc_score(y_te, p)),
                        "mean_pred": float(p.mean()),
                        "observed": float(y_te.mean()),
                        "level_gap": float(abs(p.mean() - y_te.mean())),
                        "capture": {f"{c:.2f}": capture(y_te, p, c) for c in CAPACITIES},
                    }

            results[key] = entry
            print(f"  done {key}  ({time.time() - t0:.0f}s elapsed)")

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

cap_key = f"{HEADLINE_CAPACITY:.2f}"

w("## Iteration counts")
w()
w(
    "`n_iter` is what lbfgs actually used. A value at the cap means the optimizer was "
    "still moving when it was stopped."
)
w()
w("| Point | Window | Service | Arm | Cap 1000 | Hit cap | Cap 5000 | Hit cap |")
w("|---|---:|---|---|---:|---|---:|---|")
for r in results.values():
    for arm in ("control", "loso"):
        a1 = r["arms"][f"{arm}_1000"]
        a5 = r["arms"][f"{arm}_5000"]
        w(
            f"| {r['point']} | {r['window']} | {r['service']} | {arm} | "
            f"{a1['n_iter']} | {'YES' if a1['hit_cap'] else 'no'} | "
            f"{a5['n_iter']} | {'YES' if a5['hit_cap'] else 'no'} |"
        )
w()

w("## Does the level gap move with more iterations?")
w()
w(
    "If the gap is the same at 5000 iterations as at 1000, the optimizer was not the "
    "cause. These numbers are directly comparable to the corresponding rows of "
    "`docs/16_mimic_validation.md`."
)
w()
w("| Point | Window | Service | LOSO gap 1000 | LOSO gap 5000 | Change | Observed |")
w("|---|---:|---|---:|---:|---:|---:|")
for r in results.values():
    g1 = r["arms"]["loso_1000"]["level_gap"]
    g5 = r["arms"]["loso_5000"]["level_gap"]
    w(
        f"| {r['point']} | {r['window']} | {r['service']} | {g1:.4f} | {g5:.4f} | "
        f"{g5 - g1:+.4f} | {r['arms']['loso_1000']['observed']:.4f} |"
    )
w()

w("## Capture at the headline capacity, both budgets")
w()
w("| Point | Window | Service | Ctrl 1000 | LOSO 1000 | Ctrl 5000 | LOSO 5000 |")
w("|---|---:|---|---:|---:|---:|---:|")
for r in results.values():
    w(
        f"| {r['point']} | {r['window']} | {r['service']} | "
        f"{r['arms']['control_1000']['capture'][cap_key]:.3f} | "
        f"{r['arms']['loso_1000']['capture'][cap_key]:.3f} | "
        f"{r['arms']['control_5000']['capture'][cap_key]:.3f} | "
        f"{r['arms']['loso_5000']['capture'][cap_key]:.3f} |"
    )
w()

any_cap = any(
    r["arms"][f"{arm}_1000"]["hit_cap"]
    for r in results.values() for arm in ("control", "loso")
)
gaps = np.array([
    r["arms"]["loso_5000"]["level_gap"] - r["arms"]["loso_1000"]["level_gap"]
    for r in results.values()
])

w("## Verdict")
w()
w("| Quantity | Value |")
w("|---|---:|")
w(f"| Cells tested | {len(results)} |")
w(f"| Any fit hit the 1000 iteration cap | {'YES' if any_cap else 'no'} |")
w(f"| Mean change in level gap at 5000 iterations | {gaps.mean():+.5f} |")
w(f"| Largest change in level gap | {gaps[np.argmax(np.abs(gaps))]:+.5f} |")
w()
w(
    "If no fit hit the cap and the level gap is unchanged at five times the budget, "
    "the suppressed warning was never firing and `16` stands. The level failure is a "
    "property of the held out population, not of the optimizer. The filter should still "
    "be narrowed in the scripts, because a suppressed warning that happens not to have "
    "fired is luck rather than design."
)
w()

stats["results"] = results
stats["regime"] = REGIME
stats["services"] = SERVICES
stats["max_iters"] = MAX_ITERS
stats["seed"] = SEED
stats["runtime_seconds"] = round(time.time() - t0, 1)

(DOCS / "16b_mimic_convergence.md").write_text("\n".join(lines), encoding="utf-8")
(CACHE / "mimic_convergence_stats.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")

print()
print(f"Total runtime: {time.time() - t0:.0f}s")
print("Wrote docs/16b_mimic_convergence.md")
print("Wrote cache/mimic_convergence_stats.json")
