"""
16c_mimic_service_overlap.py

Corrects a reading hazard in `16` without rerunning it.

THE PROBLEM
===========
`16` applied a fixed eligibility rule to every cell: a service is tested if it has at
least 5,000 admissions and 500 events. Regime B assumes 211,655 censored admissions are
negatives, which enlarges every service and pushes smaller ones over the threshold. The
result is that regime B qualified sixteen services while regimes A and C qualified nine.

`16`'s tables therefore place regime B rows alongside regime A and C rows as though they
were comparable. They are not. Part of any apparent difference between regimes is a
difference in which services were eligible to be tested, not a difference in how the model
transfers.

`14` already established that the censoring choice moves the reported rate, the identity
of the top decile, and the measured discrimination. Service eligibility is a fourth face
of the same choice and it should be labelled rather than left for a reader to trip over.

WHY THIS IS A SEPARATE SCRIPT
=============================
`16` took roughly eighteen hours, almost all of it in the two discharge regime B cells
where the working set appears to have exceeded memory. Every number needed here is already
in `cache/mimic_validation_stats.json`. Nothing is refitted.

`16_mimic_validation.py` is left unmodified. Editing it without rerunning would produce a
script that no longer generates its own doc, which is worse than an addendum.

WHAT IT REPORTS
===============
    Which services qualify under each regime, and the intersection common to all three.

    The transfer penalty summary restricted to that intersection, which is the comparison
    that is actually like for like.

    The regime B only services reported separately, since they are smaller and their
    penalties are noisier.

Usage:
    python 16c_mimic_service_overlap.py

Reads:
    cache/mimic_validation_stats.json

Writes:
    docs/16c_mimic_service_overlap.md
"""

import json
import sys
from pathlib import Path

import numpy as np

DOCS = Path("docs")
CACHE = Path("cache")

POINTS = ["at_admission", "at_discharge"]
REGIMES = ["A", "B", "C"]
WINDOWS = [30, 90]
HEADLINE_CAPACITY = "0.10"

lines = []


def w(s=""):
    lines.append(s)
    print(s)


path = CACHE / "mimic_validation_stats.json"
if not path.exists():
    sys.exit(f"\nMissing {path}. `16_mimic_validation.py` writes it.")

blob = json.loads(path.read_text(encoding="utf-8"))
results = blob["results"]
tol = blob["thresholds"]["capture_tolerance"]
lvl_tol = blob["thresholds"]["level_tolerance"]

tested = {}
for r in results.values():
    tested.setdefault((r["point"], r["regime"], r["window"]), set()).add(r["service"])


def delta(r):
    c = r["logit"]["control"]["capture"][HEADLINE_CAPACITY]
    l = r["logit"]["loso"]["capture"][HEADLINE_CAPACITY]
    return l - c


def level_gap(r):
    return abs(r["logit"]["loso"]["mean_pred"] - r["logit"]["loso"]["observed"])


w("# 16c. Service eligibility differs by regime")
w()
w("Generated by `16c_mimic_service_overlap.py`. Do not edit by hand.")
w()
w(
    "An addendum to `16`, computed from its cached output. Nothing is refitted. `16` "
    "itself is unmodified."
)
w()
w(
    "`16` tested any service with at least "
    f"{blob['thresholds']['min_service_n']:,} admissions and "
    f"{blob['thresholds']['min_service_events']:,} events. Regime B assumes 211,655 "
    "censored admissions are negatives, which enlarges every service and lifts smaller "
    "ones over that bar. Regime B therefore tested more services than A and C, and the "
    "regime rows in `16` are not directly comparable."
)
w()

w("## Services tested per cell")
w()
w("| Point | Window | Regime A | Regime B | Regime C |")
w("|---|---:|---:|---:|---:|")
for point in POINTS:
    for wd in WINDOWS:
        counts = " | ".join(
            str(len(tested.get((point, r, wd), set()))) for r in REGIMES
        )
        w(f"| {point} | {wd} | {counts} |")
w()

w("## The common set")
w()
for point in POINTS:
    for wd in WINDOWS:
        sets = [tested.get((point, r, wd), set()) for r in REGIMES]
        common = set.intersection(*sets) if all(sets) else set()
        b_only = sets[1] - (sets[0] | sets[2])
        w(f"**{point}, {wd} day**")
        w()
        w(f"Common to all three regimes ({len(common)}): {', '.join(sorted(common))}")
        w(f"Regime B only ({len(b_only)}): {', '.join(sorted(b_only)) or 'none'}")
        w()

w("## Transfer penalty, restricted to the common set")
w()
w(
    "This is the like for like comparison across regimes. Capture delta is the LOSO minus "
    "control capture at the 10% capacity, so more negative is a larger penalty."
)
w()
w("| Point | Window | Regime | Services | Mean delta | Worst delta | Level transfers |")
w("|---|---:|---|---:|---:|---:|---:|")
for point in POINTS:
    for wd in WINDOWS:
        sets = [tested.get((point, r, wd), set()) for r in REGIMES]
        common = set.intersection(*sets) if all(sets) else set()
        for regime in REGIMES:
            rows = [
                r for r in results.values()
                if r["point"] == point and r["regime"] == regime
                and r["window"] == wd and r["service"] in common
            ]
            if not rows:
                continue
            d = np.array([delta(r) for r in rows])
            lv = np.array([level_gap(r) for r in rows])
            w(
                f"| {point} | {wd} | {regime} | {len(rows)} | {d.mean():+.4f} | "
                f"{d.min():+.4f} | {int((lv <= lvl_tol).sum())} of {len(rows)} |"
            )
w()

w("## Regime B only services, reported separately")
w()
w(
    "These exist as testable services solely because regime B counts censored admissions "
    "as negatives. They are smaller and their penalties are correspondingly noisier."
)
w()
w("| Point | Window | Service | Capture delta | Level gap |")
w("|---|---:|---|---:|---:|")
any_b = False
for point in POINTS:
    for wd in WINDOWS:
        sets = [tested.get((point, r, wd), set()) for r in REGIMES]
        b_only = sets[1] - (sets[0] | sets[2]) if all(sets) else set()
        for r in results.values():
            if (r["point"] == point and r["regime"] == "B"
                    and r["window"] == wd and r["service"] in b_only):
                any_b = True
                w(
                    f"| {point} | {wd} | {r['service']} | {delta(r):+.4f} | "
                    f"{level_gap(r):.4f} |"
                )
if not any_b:
    w("| | | none | | |")
w()

all_rows = list(results.values())
all_d = np.array([delta(r) for r in all_rows])
common_rows = []
for point in POINTS:
    for wd in WINDOWS:
        sets = [tested.get((point, r, wd), set()) for r in REGIMES]
        common = set.intersection(*sets) if all(sets) else set()
        common_rows += [
            r for r in all_rows
            if r["point"] == point and r["window"] == wd and r["service"] in common
        ]
common_d = np.array([delta(r) for r in common_rows]) if common_rows else np.array([])

w("## Does the correction change the headline?")
w()
w("| Set | Cells | Mean capture delta | Worst |")
w("|---|---:|---:|---:|")
w(f"| All cells as reported in `16` | {len(all_d)} | {all_d.mean():+.4f} | {all_d.min():+.4f} |")
if len(common_d):
    w(f"| Common service set only | {len(common_d)} | {common_d.mean():+.4f} | {common_d.min():+.4f} |")
w()
w(
    "If the two rows agree, `16`'s headline survives and the eligibility difference is a "
    "labelling matter rather than a correction. If they diverge, the cross regime reading "
    "in `16` should be replaced by the common set figures and this addendum cited at that "
    "point in the doc."
)
w()

(DOCS / "16c_mimic_service_overlap.md").write_text("\n".join(lines), encoding="utf-8")
print()
print("Wrote docs/16c_mimic_service_overlap.md")
